### ISSUE TITLE
linux410-vbox-module not installed

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#102]
https://forum.manjaro.org/t/manjaro-architect-0-8/19291/
I'm not sure if this is related to the earlier attempt to install with **linux411**. He says he reinstalled but I'm not sure if linux411 might still have been present on target.

**Comment by Onfroygmx** [comment]
After some further looking into the issue.
Once the virtualbox-guest modules are installed the "vboxsf" group is not created and not added to the startup services and default users (systemd and openrc).
If done manually after the install this is logical, there is no way to know what to do.
If this needs to be handled by the installer some extra steps are required.
Personnaly, this is needed for testing on VM only and the architect installer user must know a bit what he is doing, so the easiest is to remove the option (I don't know how it behaves under other VM solutions).

**Comment by Chrysostomus** [comment]
I think this is caused by user not using the mhwd driver menu. #106 would make it more difficult to miss.

**Comment by Onfroygmx** [comment]
I installed with mhwd afterwards but it only pics up the video drivers and still not starts the vboxservice. I will retry a clean install later today with the network drivers, but the service is not started, the modules are loaded corectly in the kernel.

**Comment by oberon-manjaro** [comment]
We haven't confirmed this issue. Everything seems to be working for me and others.
Do you have more information on this @Onfroygmx

**Comment by Onfroygmx** [comment]
Kernel modules still don't get installed on base install so there is not way it can work.

They get installed but service is not activated with drivers now.
[m-a.txt](https://github.com/Chrysostomus/manjaro-architect/files/870006/m-a.txt)
[pacman.txt](https://github.com/Chrysostomus/manjaro-architect/files/870007/pacman.txt)

**Comment by oberon-manjaro** [comment]
I think I completely do not understand what is the issue here. Can you please try to explain to me again exactly what you are trying to install, how and why?
In your original post on the forum you wrote
> After reboot the the DM is not loaded. If I install the vbox modules not installed previously and reboot then the DM shows up correctly but the vboxservice is not started completely and the shared folders are not mounted.

Now when I install any openrc system and install vbox-driver via the video-driver install, everything is fine and the guest starts fine in vbox. I am confused.

**Comment by oberon-manjaro** [comment]
Are you trying to install base only without installing the video-driver? Why?

**Comment by Onfroygmx** [comment]
Close it then if it works.

**Comment by oberon-manjaro** [comment]
Well I have no problem to fix an issue. My problem here is just that I don't understand what it is ... :wink:
