### ISSUE TITLE
review "common packages" selection

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#103]
The preselection seems a bit random. Ideally we'd filter out packages already installed... :wink: 
https://forum.manjaro.org/t/manjaro-architect-0-8/19291/6

**Comment by papajoker** [comment]
i dont understand what filter, one exemple with filter last package and on/off, a dyn menus as :  

   ```
install_base() { #util-base.sh

    local options=() default='off'
    options+=("$kernel-headers" "-" off)
    options+=("$kernel-acpi_call" "-" off)
    options+=("$kernel-ndiswrapper" "-" off)
    options+=("$kernel-broadcom-wl" "-" off)
    options+=("$kernel-r8168" "-" off)
    options+=("$kernel-rt3562sta" "-" off)
    options+=("$kernel-tp_smapi" "-" off)
    options+=("$kernel-vhba-module" "-" off)
    [[ "VM" == "VM" ]] && default='on' || default='off'
    options+=("$kernel-virtualbox-guest-modules" "-" "$default")
    options+=("$kernel-virtualbox-host-modules" "-" "$default")
    options+=("$kernel-spl" "-" off)
    # if $kernel-zfs in not in file ? if ! grep "${kernel}-zfs" afile; then
    # or in repos :
    [[ $(pacman -Ssq "^${kernel}-zfs$") == "${kernel}-zfs" ]] && \
                  options+=("$kernel-zfs" "-" off)

    DIALOG " $_ChsAddPkgs " --checklist "\n\n$_UseSpaceBar" 0 0 "$((${#options[@]}/3))" \
          "${options[@]}" 2>/tmp/.modules
    [[ "$(</tmp/.modules)" == "" ]] && return 0
    
    ...
         cat /tmp/.modules >> /mnt/.base
   ...
```

**Comment by oberon-manjaro** [comment]
what I meant was this list of ``install_extra() ``:
```
      "manjaro-settings-manager" "-" off \
      "pamac" "-" off \
      "octopi" "-" off \
      "pacli" "-" off \
      "pacui" "-" off \
      "fish" "-" off \
      "fisherman" "-" off \
      "zsh" "-" on \
      "zsh-completions" "-" on \
      "manjaro-zsh-config" "-" on \
      "grml-zsh-config" "-" off \
      "mhwd-chroot" "-" off \
      "bmenu" "-" on \
      "clonezilla" "-" off \
      "snapper" "-" off \
      "snap-pac" "-" off \
      "manjaro-tools-iso" "-" off \
      "manjaro-tools-base" "-" off \
      "manjaro-tools-pkg" "-" off 2>${PACKAGES}
```
Depending on the profile installed a bunch of them will always be already installed and the user will very likely not know that. So instead of offering them as duplicates it would be good to remove the already installed ones. But this can likely simply be achieved with a for loop with ``pacman -Q`` I think

**Comment by papajoker** [comment]
ok is the same code ;)

```
local options=() nb=0
...
! grep -E " zsh |^zsh$" /mnt/.afile && options+=("zsh" "-" on)
# or find in local not chroot :(
! pacman -Qq "^$zsh$" >/dev/null && options+=("zsh" "-" on)
...

nb="$((${#options[@]}/3))"; (( nb>20 )) && nb=20 # if list too long limit

DIALOG " $_InstComTitle " --checklist "\n$_InstComBody\n\n$_UseSpaceBar" 0 50 $nb \
      "${options[@]}" 2>${PACKAGES}
```

**Comment by oberon-manjaro** [comment]
Ok. I think I understand - will try that :wink: We can in fact grep **/mnt/.base** for the packages in question.

**Comment by oberon-manjaro** [comment]
What is this ``"^$zsh$"?`` What does it do compared to simply plain``pacman -Qq zsh`` ?

**Comment by papajoker** [comment]
oops, its a copy/paste from prev post with `pacman -Ssq` with pacman -Qq we have no reason to use it

**Comment by oberon-manjaro** [comment]
What is it anyway?

**Comment by papajoker** [comment]
^ = line begining by
$ = line end by

for exemple in `grep -E " zsh |^zsh$" /mnt/.afile`
we find "[space]zsh[space]  or ^zsh$" a line with exactly zsh (not zsh_extension !)

**Comment by oberon-manjaro** [comment]
Shouldn't be a problem to do like this, right?
```
cpkgs="manjaro-settings-manager pamac octopi pacli pacui fish fisherman zsh zsh-completions \
  manjaro-zsh-config mhwd-chroot bmenu clonezilla snapper snap-pac manjaro-tools-iso manjaro-tools-base manjaro-tools-pkg"

for p in ${cpkgs}; do
    ! pacman -Qq "$p" >/dev/null && options+=("$p" "-" off)
done
```

**Comment by papajoker** [comment]
not tested, more simple is to create a small script with echo at end ;)
create a array cpkgs=(manjaro-settings-manager pamac octopi pacli )
for a array , its for p in `"${cpkgs[@]}"` NOT "${cpkgs}"

```
for p in "${cpkgs[@]}"; do
    ! pacman -Qq "$p" &>/dev/null && options+=("$p" "-" off)
done
```

**Comment by oberon-manjaro** [comment]
Awesome! Works perfectly. Just tested locally.:stuck_out_tongue_winking_eye: 

![](http://imgur.com/FJnRoy5.png)

The rest I have installed apparently :laughing: 
Btw. No problem also with ${cpkgs} :wink: ; but maybe that's "bad practice" :skull_and_crossbones:

**Comment by papajoker** [comment]
you run `pacman` in host not in chroot !!!!!!!! use basestrap ?

${cpkgs} its a string, for x in, you loop on word, the separator is the variable IFS
with array, we dont use IFS 
sometime IFS is ' ', but can change in the code by '\n' or ';'and in this cas, your code not run good

**Comment by oberon-manjaro** [comment]
yes. just a test. will do with grep:
```
install_extra() {
    # Offer to install various "common" packages.
    local options=() nb=0
    cpkgs="manjaro-settings-manager pamac octopi pacli pacui fish fisherman zsh zsh-completions \
      manjaro-zsh-config mhwd-chroot bmenu clonezilla snapper snap-pac manjaro-tools-iso manjaro-tools-base manjaro-tools-pkg"
    for p in ${cpkgs[@]}; do
        ! grep "$p" /mnt/.base && options+=("$p" "" off)
    done
    DIALOG " $_InstComTitle " --checklist "\n$_InstComBody\n\n$_UseSpaceBar" 0 50 $nb 2>${PACKAGES}

    # If at least one package, install.
    if [[ $(cat ${PACKAGES}) != "" ]]; then
        clear
        basestrap -i ${MOUNTPOINT} $(cat ${PACKAGES}) 2>$ERR
        check_for_error "basestrap -i ${MOUNTPOINT} $(cat ${PACKAGES})" "$?"
    fi
}
```

**Comment by papajoker** [comment]
I always use arrays to avoid getting trapped ;)
With your code `for` find words with the space separator or return (IFS var);

With my way, I can write (not in our case)
`Array = (one two "and tree")`
I have **3** items, with your syntax i have **4** items!

-------------

`nb="$((${#options[@]}/3))"; ` return number of elements in array /3, where is nb in our code ?
AND no pass options array in dialog ???????

--------------------------
NO `grep "$p" ` you return ok for octopi-notifier (view regex post up)
as zsh return ok for  zsh and zsh-completions
There is a risk (here very minor)

grep is more speed that basestrap !

**Comment by oberon-manjaro** [comment]
:+1: thank you. :smiley:

**Comment by Chrysostomus** [comment]
Is it possible to grep -v -f with arrays? Can array be used as a pattern group with -f flag like a file can?

**Comment by papajoker** [comment]
as this ? http://stackoverflow.com/questions/38114906/get-only-those-elements-from-list-x-which-are-not-in-list-y?noredirect=1&lq=1

    pkgs=(pacman pacli pacui "fish and chips"  )
    echo ${pkgs[@]} # array as one line
    printf '%s\n' "${pkgs[@]}" # on item by line (here 4 lines)

**Comment by Chrysostomus** [comment]
Ooh, nice...
