### ISSUE TITLE
Semiautomate driver installation 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#106]
1) automatically install network drivers after base installation. Modify the current network driver function to use for loop instead of menu and place it at the end of install_base. Something like this:

```
install_network_drivers() {
    if [[ $(mhwd -l | awk '/network-/' | wc -l) -gt 0 ]]; then 
        for driver in $(mhwd -l | awk '/network-/{print $1}') do
          mhwd -f -i pci $driver
        done
    fi
}
```

2) trigger video driver installation at the end of manjaro-desktop installation. A single list with both manual options and free/nonfree. It is needed if and only if user chooses graphical user interface.

**Comment by Chrysostomus** [comment]
sould be done now

**Comment by oberon-manjaro** [comment]
Something went wrong there apparently! :wink: 
I can see that you removed install_drivers_menu and added automatic network driver installation.
But as far as I can see you didn't add any graphics-drivers installation anywhere?

**Comment by oberon-manjaro** [comment]
Not sure what your plans were with the advanced installation menu. For now I just added **install_drivers_menu** there, because otherwise currently there's no driver installation at all for unconfigured desktop... :wink:

**Comment by oberon-manjaro** [comment]
Automatic is good, but we need to keep a place where manual driver installation is still possible for when you change your mind, or something went wrong or you want to repair an installation... ...
Advanced menu for now is a good place anyway.
