### ISSUE TITLE
filtering already mounted partitions has stopped working

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#107]
When I look at the commits, util-disk has not been touched for a week, yet for some reason already mounted partitions are no longer filtered out.
After mounting the /root partition I am still offered the same partition again for swap and boot ...
What can be wrong?

**Comment by Chrysostomus** [comment]
I haven't noticed the issue. I'll look into it

**Comment by oberon-manjaro** [comment]
I could swear that just recently it was still working - which I know doesn't seem to make sense ;)

**Comment by papajoker** [comment]
- only one filter before show partitions but not after mount root, not after mount swap, not after efi
exist a code, but run nothing ?  : 

       PARTITIONS=$(echo $PARTITIONS | sed "s~${PARTITION} [0-9]*[G-M]~~" | sed "s~${PARTITION} [0-9]*\.[0-9]*[G-M]~~" | sed s~${PARTITION}$' -'~~)
       NUMBER_PARTITIONS=$(( NUMBER_PARTITIONS - 1 ))

    I use function `delete_partition_in_list() `and its ok

- one problem, many `return 0` with efi partitions -> can never select others partitions if user dont format efi
remove returns and restructure
