### ISSUE TITLE
terminus font and languages

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#109]
Yesterday I have played with displaying different language versions in the console and adjusted terminus versions accordingly in [``select_language()``](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util.sh#L240)
Now I just saw that in [set_keymap](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-base.sh#L568) font is defined based on screen resolution regardless of language.
Not sure how this can best be adjusted...

**Comment by Chrysostomus** [comment]
Sure can. The size number is consistent across options, we can determine that with screen size and the rest with language.

**Comment by oberon-manjaro** [comment]
Should we just define the correct font based on screensize and language immediately in select_language() and then just use already defined $FONT in set_keymap() without interfering again?
Or just make set_keymap() a part of select_language()(?

**Comment by oberon-manjaro** [comment]
We could just compose $FONT based on initial information like something
``FONT="ter-${lang}${size}n"``

**Comment by oberon-manjaro** [comment]
I like the idea of moving set_keymap() to inital language selection and have one less menu entry in the programm. Should I do that?

**Comment by Chrysostomus** [comment]
Keymap should not be selected based on language. Our language selection is narrow, and many people prefer to have different keymap and language.

**Comment by oberon-manjaro** [comment]
What I mean is when the app launches, add a keymap selection dialog right after language selection.

**Comment by Chrysostomus** [comment]
That is good.

**Comment by oberon-manjaro** [comment]
See PR https://github.com/Chrysostomus/manjaro-architect/pull/110
