### ISSUE TITLE
proper way to abort

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#117]
When during for example base installation I want to abort the whole installation and hit Ctrl+c, currently package installation is aborted, BUT the function continues.
Meaning even though package installation is interrupted we still attempt to amend mkinitcpio, copy config and, attempt to install network drivers and what's certainly bad: We touch **/mnt/.base_installed**!
There must be a proper way to capture abortion, right? @papajoker ?

**Comment by Chrysostomus** [comment]
After command check exit status with $?. If it is certain non 0 values, check for error and return $?

**Comment by oberon-manjaro** [comment]
we already have
```
basestrap ${MOUNTPOINT} $(cat /mnt/.base) 2>$ERR
check_for_error "install basepkgs" $?
```
Apparently that's not enough...

**Comment by oberon-manjaro** [comment]
Ah. But we can still ``$?`` after ``check_for_error`` since it has
```
if [[  "${_function_menu}" != "SKIP" ]]; then
    DIALOG " $_ErrTitle " --msgbox "\n${_msg}\n" 0 0
    # return error for return to parent menu
    return $_err
fi
```

**Comment by oberon-manjaro** [comment]
But then what ``check_for_error`` already does, why isn't that enough to exit the function anyway?

**Comment by papajoker** [comment]
check_for_error return the error pass in parameter

```
check_for_error "install basepkgs" $? || return 1
```

but if you dont view a dialog error is that [basestrap](https://github.com/manjaro/manjaro-tools/blob/master/bin/basestrap.in) return always 0 :pensive:

**Comment by oberon-manjaro** [comment]
no. I do see an error window. But I forgot that ``check_for_error()``'s ``return n`` only returns us again to ``install_base()`` from where it has been called.
So we just need to proceed conditionally. ``return 0`` would do I think.
Like this?
```
do_something 2>$ERR
check_for_error "something" $? || return 0
do_more
```
Should **not** execute ``do_more`` if ``do_something`` throws an error, right?
