### ISSUE TITLE
point release

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#119]
I've just uploaded a **-dev** package of the latest git version, that is **0.8.0.r85.gb369839**.
Maybe with all the additions, fixes and changes since the **0.8.0** release it would be a good idea to do a point release **0.8.1** for the stable package?
We could just wait after some test installs have passed tonight and do that later tonight or tomorrow...

**Comment by papajoker** [comment]
good time for translate alors  :)
