### ISSUE TITLE
rescue tool option

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#123]
Currently it will not be possible to use the architect for repairing an existing system that has not been installed originally with the architect because of ``check_base`` and the not existing **/mnt/.base_installed** "marker".
We should find a way to offer tools like bootloader installation, fstab generation for existing installs.
Maybe just an additional entry in the main menu with a confirmation dialog about possible risks of damaging an existing install lalala ?

**Comment by Chrysostomus** [comment]
Option under advanced menu to touch /mnt/.base_installed?

**Comment by oberon-manjaro** [comment]
Not ideal... You would need to "prepare installation" first , which doesn't sound right, and also final check will complain for example about no graphics driver installed - to avoid that we'd have to also touch **/mnt/.video_installed** - kind of dirty approach :wink: 
Why not just a separate menu entry in the main menu? It will basically just call the same functions as installation. check_base can then just be bypassed with an extra var passed on, functions blocked from inside can then simply run with something like ``if [[ $rescue == "y" ]]; then``
They'd just need to check_mount.
Would be really nice to have all the helpfull things for a rescue case in one place. Stuff like
```
rescue_tools
├── mount partitions
├── install bootloader
├── generate fstab
└── edit configs
```
possibly also ``install drivers``?

**Comment by Chrysostomus** [comment]
Alternatively we could display just the rescue menu when run with the flag --rescue

**Comment by oberon-manjaro** [comment]
sure! maybe good to not overcrowd the regular menu.
analog to ``setup`` wrapper, we can also just use another command ``rescue`` or `repair`` and invoke the ``-r|--rescue`` option with that one. ``setup -r`` would also work since it passes on arguments anyway.
I'll cook something up :)

**Comment by Chrysostomus** [comment]
I like setup -r

**Comment by papajoker** [comment]
or ? a simple recue after update : blocked at boot
-> graphic driver, dm (with autodetect) , ...

------------------
in ini, we have a simple [function](https://github.com/Chrysostomus/manjaro-architect/blob/ini/lib/util.sh#L160) to add -r|--rescue

------------------

This can be a way to test the file menu-engine.sh without risk, just create a template rescue in /data/ and call show_menu (id_template_mainmenu) ?
https://github.com/papajoker/manjaro-architect/tree/dynmenu/lib

**Comment by Chrysostomus** [comment]
Excellent idea!

**Comment by papajoker** [comment]
branch rescue created (from dynmenu)
just a quick model for demo/start (change /data/rescue.menu) https://github.com/papajoker/manjaro-architect/issues/1

**Comment by oberon-manjaro** [comment]
I just tried to understand what I see in branch rescue but I have to say I'm a bit overwhelmed with all the new dynamic functionality here...
Honestly I don't know if we will need several different menus in the future, actually I'd just like to create a simple modified rescue menu by re-arranging some of the already existing functions of the installer, which I think would in fact just be a matter of half an hour or so ;)
While I am convinced that the new code can provide a lot of flexibility in the future, right now I am just lost ...
@papajoker would you maybe just like to finish a working rescue menu version? Or should I just build one with our existing old tools? I just don't understand enough to attempt accomplishing this with the new dynamic features, I'm afraid. Maybe we need to be a bit careful not to introduce too many changes and features at the same time?

**Comment by papajoker** [comment]
Using dynamic menu features with rescue was an excuse to test it;)

The goal is not to recreate all menus! actual rescue.menu is false ;)
If the rescue functions already exist in the present code, just modify the model (data/rescue.menu) and put the right function (classic menu or directly working function ) in front of the item (delete these sub-items if they exist )
one item call a function (after char ";"), if item have sub items, so this item call automatically show_menu "his submenu"
in model "--" is one level

for exemple, for to edit config at main menu, re-use the existing function_menu :

      ----econf ; edit_configs

and in .trans, for exemple

    $_econfMenuTitle="Edit config"
    $_econfMenuBody="if you want mofify ..."

I just tried to write a function to only mount the partitions because it seems to me that this does not exist in the current code: only creation? Unfortunately I am blocked: I can mount the home but not the root :pensive:

**Comment by Chrysostomus** [comment]
The functionality exists, choosing the option "Skip" in filesystem menu mounts partition without formatting it

**Comment by papajoker** [comment]
ok ! I did not understand that "skip" meant to mount only, I thought rather to cancel :blush: is not in body text. "mount only" is best as label ?
But can we use the same menu? Here we propose by default to format it is very dangerous ! for a rescue is not reasonable

I will try to modify this menu, if we pass in parameter "rescue" that only skip is proposed and my type of formatting,  It is also necessary to change the texts ...

**Comment by Chrysostomus** [comment]
I think the warning messages are very clear, so I don't think it is a big issue. Skip is even the default option. What of we just modified "Skip" to read "Do not format"? Then it would be more clear maybe?

**Comment by papajoker** [comment]
i never read all the dialog before partition choice :confused: speed enter !
:+1: i vote for  "Do not format", I'm sure to not do a stupid thing

no we can use the same fonction mount_partitions()  bac8f54a72edde47eea4203c2d98e27266deaa98 , skip text dialog before et skip dialog format

**Comment by oberon-manjaro** [comment]
I have updated rescue branch with master - hope I didn't revert any necessary changes :wink: 
Just built the branch and tried running it with ``manjaro-architect -r`` and ``manjaro-architect --rescue`` but can't see any difference - same menu as unsual... What am I missing?

**Comment by papajoker** [comment]
i have never use pacman for install manjaro-architect, i use always custum dev.sh from manjaro-architect.in
Its the makefile ! /usr/share/manjaro-architect/rescue.menu not installed
fixed 300960a4b15bb00a58c5503d263b380626bcca9b

**Comment by oberon-manjaro** [comment]
Ok. Thanks. It's working now. I'm afraid I don't understand what "old mount" is... :wink: ?

**Comment by papajoker** [comment]
its my [old](https://github.com/Chrysostomus/manjaro-architect/blob/96dde4db58770c9b3eb7210c9aa45b43982be49e/lib/util-rescue.sh#L13) mount partitions before modify the fonction in disk-utils https://github.com/Chrysostomus/manjaro-architect/issues/123#issuecomment-288256537

ressue.menu is not make

**Comment by oberon-manjaro** [comment]
Somehow I currently get both in the menu:

![](http://imgur.com/rPWgaAf.png)

Also the menu entries don't seem to do anything, including the submenu entries in "install base" while they are all existing functions.

**Comment by papajoker** [comment]
sorry for french (but if more simple...)
>Uniquement la première ligne 1) et la dernière 6) fonctionnent, tout le menu est a faire en éditant le fichier .menu , je te laisse justement un fichier mon valide pour faire des tests et entrer ce que tu désires (et comprendre la simplicité ?), la forme est:
level(--) item(clé dans fichier .trans) ; fonction bash
2) is a [old](https://github.com/Chrysostomus/manjaro-architect/blob/96dde4db58770c9b3eb7210c9aa45b43982be49e/lib/util-rescue.sh#L13) test, now fonction not exist

>submenu entries in "install base" while they are all existing functions.
no i dont link function to this items !

```
----InstBs                   ; check_r_mounted ;
------Mirrorlisting
------refresh keys
------bootloader
------done                ; mnu_return 97
```
for link a function to item, add after car ";" the call shell function (menu existing or working)
