### ISSUE TITLE
rank_mirrors is broken 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#127]
Most likely the branch choice sets empty string as branch. 

```
rank_mirrors() {
    #Choose the branch for mirrorlist
    DIALOG " $_MirrorBranch " --radiolist "\n$_UseSpaceBar\n " 0 0 3 \
      "stable" "-" on \
      "testing" "-" off \
      "unstable" "-" off 2>${ANSWER}
    local branch="$(<{ANSWER})"
    clear
    if [[ ! -z ${branch} ]]; then
        pacman-mirrors -gib "${branch}"
        ini branch "${branch}"
    fi
}

```

If we are using the temporary file ${ANSWER} anyway, why not just cat it like all the other options do? 

Also, we should have some kind of infobox telling the user how to exit the mirror choice screen. It is quite unintuitive.

**Comment by Chrysostomus** [comment]
Also, why 

[[ ! -z ${branch} ]] instead of ! [[ -z ${branch} ]]?

**Comment by oberon-manjaro** [comment]
I think this is just a result of many changes to and fro... ;-)
``[[ ! -z ${branch} ]] instead of ! [[ -z ${branch} ]]`` should be the same, no?

**Comment by Chrysostomus** [comment]
No idea. Maybe?

**Comment by oberon-manjaro** [comment]
I cannot check the code right now properly, I'm not at the computer. But I think reason for the dedicated var is that we use it later when we ``sed`` target **pacman-mirrors.conf**.
But with latest development we can use ini file of course

**Comment by oberon-manjaro** [comment]
it's the same if you negate the test or the content of the test.

**Comment by oberon-manjaro** [comment]
```
$ ! [[ ! "yes" == "yes" ]] && echo "true"
true
```

**Comment by Chrysostomus** [comment]
I'll try to catch up on how this ini file works again...

**Comment by oberon-manjaro** [comment]
How is it broken? The code of this dialog looks right to me...

**Comment by Chrysostomus** [comment]
Mirror ranking is not triggered

**Comment by papajoker** [comment]
sorry its the char "$" forgotten
not `local branch="$(<{ANSWER})"`
but : 

     local branch="$(<${ANSWER})" # redirect file $ANSWER to variable

and if you want, we can replace

    if [[ ! -z ${branch} ]]; then # by
    if [[ -n ${branch} ]]; then

**Comment by oberon-manjaro** [comment]
working now in any case.
I think I don't understand what you mean about "telling the user how to exit the mirror choice screen"
Which screen do you mean?

**Comment by Chrysostomus** [comment]
The terminal screen that lists ranked mirrors for user choice. It has no exit button, does not respond to enter, esc, q, ctrl+X or other common keybindings to quit terminal applications. Finally I found that you can quit by scrolling to the bottom of the list and pressing enter. I think user should not have to guess this.

**Comment by oberon-manjaro** [comment]
https://github.com/Chrysostomus/manjaro-architect/issues/132
