### ISSUE TITLE
Desktop package list is not emptied when switching desktops

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#128]
I tried to install mate profile, and when it failed, bspwm profile. Mate packages were also on the list, so any further profile attempts fail

**Comment by oberon-manjaro** [comment]
If we just clear **/mnt/.base** at the beginning of ``install_manjaro_de_wm()`` we will lose the possibility to sort out already installed packages like we do at the moment. I think we will need to store base packages in a separate file and then grep -v it against the desktop packages list.

**Comment by oberon-manjaro** [comment]
I think this should be fixed now on **pkgs_lists** branch. Also reinstalling of base packages should now be eliminated. Have a look!
I have also moved excluding grub and adding nilfs-utils to base install and evaluate openrc to desktop install.
I've built **manjaro-architect-exp-0.8.2.r20.gac4e9d3** from this branch, if you want to try it.

**Comment by oberon-manjaro** [comment]
I also just realized that set keymap was not really working :stuck_out_tongue_winking_eye: . Fixed in the next commit and will port that to master also of course.

**Comment by Chrysostomus** [comment]
I have lately hard time testing anything. All my attempts fail at desktop installation with 255 error. I think I have weird remnant files somewhere causing the problem.

**Comment by Chrysostomus** [comment]
I can't find that -exp package from the repos

**Comment by oberon-manjaro** [comment]
It's in unstable branch. Your server maybe not updated. What is this 255 error? I got it too when trying to an unformatted partition with another DE already installed. just package conflicts?

**Comment by oberon-manjaro** [comment]
Maybe error messages would be a bit more informative if we switched to using pacman for desktop packages?

**Comment by Chrysostomus** [comment]
Unlikely. I have now gotten it like 6 times on newly formatted partition. 

Thing is, basestrap already uses pacman and gives its output.

**Comment by Chrysostomus** [comment]
But I have read of people installing with this in the meantime, so it seems only I have the issue. With repo version and git version, stable and developement profiles, systemd and openrc.

**Comment by oberon-manjaro** [comment]
Hmm how strange! I also just successfully made an install yesterday with latest git version... Do you know if pkgs get downloaded ok in the first place? You should be able to see that.

**Comment by Chrysostomus** [comment]
Base installation works as usual. No pacman output is presented by desktop installation. Package list does get generated and filtered. 

I though it must be something with my profiles directory, but removing it and trying again did not do the trick.

**Comment by oberon-manjaro** [comment]
Why don't you just edit that basestrap line and redirect all output to log so you can see what's going on there!

**Comment by oberon-manjaro** [comment]
Check everything in your **/tmp** maybe!? Btw. Do you know where these files **/tmp/cmd...** come from? I have one here for example **/tmp/cmd_dbus_rc** containing ``error: package 'dbus-openrc' was not found``

**Comment by Chrysostomus** [comment]
Okay, got now one profile working. Mate one had been failing because the repo profiles still call all -gtk3 packages even though they were renamed.

**Comment by Chrysostomus** [comment]
If it has dbus in its name, you can be sure that I have no idea what it is :)

**Comment by Chrysostomus** [comment]
Now testing why everything has been failing with openrc...

**Comment by Chrysostomus** [comment]
Aand openrc stuff fails because all the elogind stuff is not yet at my mirror it seems.

**Comment by oberon-manjaro** [comment]
Switch to netzspielplatz!
I just now did an i3 openrc. No issues except the clock displays total non-sense - at least in vbox ... It's not even off by hours but just complete rubbish. Right now it's supposedly 3:26, while in fact it is 10:54 😉  I guess something with utc is off, but maybe not even related to the installer.

**Comment by Chrysostomus** [comment]
It's surprisingly slow from Siberia, but I'll add it in...

**Comment by oberon-manjaro** [comment]
Or check with the mirror page to find something updated with unstable branch:
http://repo.manjaro.org/

**Comment by Chrysostomus** [comment]
Halifax seemed to be the best choice

**Comment by Chrysostomus** [comment]
Everything is now working with up to date mirrors. It's funny how problems just get solved like magic when you talk about them and do something about them...

**Comment by oberon-manjaro** [comment]
:laughing:
So I think we can merge this, ok?

**Comment by Chrysostomus** [comment]
Yes
