### ISSUE TITLE
terminus-font currently not installed by all profiles

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#130]
Currently we configure target consolefont assuming **terminus-font** is present, but in fact it is not installed by every profile: Xfce and KDE only list it with ``>extra`` flag.
https://forum.manjaro.org/t/manjaro-architect-0-8/19291/229
We should either remove the flags there, or not pre-configure it like that.

**Comment by Chrysostomus** [comment]
Maybe move font setting after desktop installation and check if terminus is installed?

**Comment by oberon-manjaro** [comment]
https://github.com/manjaro/iso-profiles/issues/36
