### ISSUE TITLE
re-consider handling of openrc profiles

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#131]
With latest elogind development we now have ``>openrc`` flags added again to all profiles while I am not at all convinced that all of them actually work with openrc.
How should the installer approach this? Ideally we should only offer working combinations, I think.
So, should we try to evaluate what actually works and just block the rest in a hard-coded manner?

**Comment by Chrysostomus** [comment]
I think we should first test if they actually work. Gentoo people have made gnome work on openrc in the past, so it is possible that some of those previously unworkable profiles actually work now.
