### ISSUE TITLE
Detect other operating systems with grub 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#15]
Currently update-grub fails when ran by the installer

**Comment by Chrysostomus** [comment]
@oberon2007  Do you know how to get update-grub working in chroot? I am trying https://www.pckr.co.uk/arch-grub-mkconfig-lvmetad-failures-inside-chroot-install/ but I have trouble implementing it in the script.

**Comment by Chrysostomus** [comment]
When done manually, the linked instruction seems to solve the error 

```
/run/lvm/lvmetad.socket: connect failed: No such file or directory
WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
```

However, I still get multiple

    ERROR: mkdir /var/lock/dmraid
and no other systems are detected.

**Comment by Chrysostomus** [comment]
I think it also works if I use systemd-nspawn instead of chroot, but that would make us depend on systemd...

**Comment by oberon-manjaro** [comment]
How exactly are you mounting partitions? How did you implement the ``--bind`` stuff?

**Comment by oberon-manjaro** [comment]
Here's another report of success with this: https://ubuntuforums.org/showthread.php?t=1965163

**Comment by Chrysostomus** [comment]
The Ubuntu guide seems to work in that it doesn't give any errors. It does not find the other systems either through.

**Comment by Chrysostomus** [comment]
```
[root@manjaro matti]# mount --bind /run  /mnt/run
[root@manjaro matti]# manjaro-chroot /mnt/ "update-grub"
Generating grub configuration file ...
Found background: /usr/share/grub/background.png
Found Intel Microcode image
Found linux image: /boot/vmlinuz-4.4-x86_64
Found initrd image: /boot/initramfs-4.4-x86_64.img
Found initrd fallback image: /boot/initramfs-4.4-x86_64-fallback.img
ERROR: mkdir /var/lock/dmraid
ERROR: mkdir /var/lock/dmraid
ERROR: mkdir /var/lock/dmraid
ERROR: mkdir /var/lock/dmraid
ERROR: mkdir /var/lock/dmraid
ERROR: mkdir /var/lock/dmraid
ERROR: mkdir /var/lock/dmraid
ERROR: mkdir /var/lock/dmraid
ERROR: mkdir /var/lock/dmraid
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
Found memtest86+ image: /boot/memtest86+/memtest.bin
done

```

Does not seem to be any better actually.

**Comment by oberon-manjaro** [comment]
I don't have any foreign OS installed... ;) but for me this works to get rid of the errors:
- chroot with **manjaro-chroot**
- use a new terminal window to ``mount --bind /run  /mnt/run``
- now run **update-grub** in the first window

**Comment by Chrysostomus** [comment]
I wonder if the problem might arise of the fact that I install on removable drive. Maybe having --removable flag in grub-install command might help...

**Comment by Chrysostomus** [comment]
Issue effects only installations on removable usb keys. Not a major problem then. Maybe we could add a information window that says: "Grub is now installed. If your other systems do not show in the grub menu, do not panic. Just boot and run 'sudo update-grub' in your manjaro installation."
