### ISSUE TITLE
Remove extra packages selection after desktop installation

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#154]
The new fzf based extra package selection should be sufficient if the user wats something more. Moving extra packages out of desktop installation would make the experience smoother. I liked to have it to spread bmenu and manjaro-zsh to new users, but it is probably better not to have this.

Any opinions on this? If there are no dissenting voices, I'll probably do this soon.

**Comment by oberon-manjaro** [comment]
I agree. Packages can so easily be installed later. It's not really a good place for advertisement of that kind I think... 😉

**Comment by Chrysostomus** [comment]
Okay, I commment it out, we can maybe use the function elsewhere. 

I think we could package the next release soon. Has important bugfix for vconsole settings, the new extra package selector (need to add fzf as a dependency) and the new chroot option. I'm still working to make the chroot option smoother. Right now it put the installer to backgound when you exit the chroot. There is an infobox telling how to get back, but it would be better if it would just return to installer straight. But once I get that in some decent shape, we could maybe do the next release?

**Comment by Chrysostomus** [comment]
Okay, done. I could not get chroot option to do what I wanted, so I added better instructions instead. As a bonus, uuser learns of the fg command.

I think it is now ready for next release.

**Comment by Chrysostomus** [comment]
I was going to update the PKGBUILD, but I discovered that I don't know how to. How do you enable the $url/archive/$pkgver.tar.gz for new $pkgver?
