### ISSUE TITLE
Displayed Version information

### ISSUE THREAD

**Issue by Onfroygmx** [Chrysostomus/aif-dev#159]
Minor:
The version information displayed at the top of the install screen does not reflect the package information.
Confusing when you want to be sure to test the correct version.
Remove that information or make it dynamic.
![versioninfo](https://cloud.githubusercontent.com/assets/25054585/26239707/624d2226-3c7e-11e7-9cf0-65cc065e15ee.png)
https://cloud.githubusercontent.com/assets/25054585/26239707/624d2226-3c7e-11e7-9cf0-65cc065e15ee.png

Info is correct on system
Name            : manjaro-architect
Version         : 0.8.11-1

and in m-a.log
    :: manjaro-architect 0.8.11-1 ::

05/19/17 08:41:11 system: UEFI, init: systemd nw-client: nmtui

**Comment by oberon-manjaro** [comment]
My bad. Didn't remove the downloaded tarball when packaging. So no matter that I had actually fixed the Makefile and release before, the tarball was still wrong 😝 Will repackage later today.

**Comment by Chrysostomus** [comment]
Maybe we could also get the version number with pacman at runtime? No need to update it then.

**Comment by oberon-manjaro** [comment]
Or sed Makefile in the PKGBUILD?

**Comment by Chrysostomus** [comment]
Sounds more complicated but fine with me. Possibly less overhead that way.

**Comment by oberon-manjaro** [comment]
Found an elegant solution now where Makefile gets the release version through git automatically 😀

**Comment by Onfroygmx** [comment]
I confirm it works
https://cloud.githubusercontent.com/assets/25054585/26266852/71e263e0-3ce7-11e7-9ce6-b0a8a90211e9.png
