### ISSUE TITLE
Error when executing bootctl install

### ISSUE THREAD

**Issue by Onfroygmx** [Chrysostomus/aif-dev#162]
Medium
05/19/17 09:43:35 ERROR [systemd-boot][1] Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
https://cloud.githubusercontent.com/assets/25054585/26243555/952a8cb6-3c8c-11e7-9668-53237e565800.png
When installing the systemd bootloader on an existing installation first the previous error/information message is displayed to the user (did it work or not?)
Then a confirmation message is displayed that the bootloader was installed successfully (no screenshot of that).
On the file system seems that the bootloader was copied correctly and that the conf files are generated correctly. 
Maybe separate bootloader installation and configuration file generation to have a better overview (conf file generation is not logged in m-a.log)

**Comment by Chrysostomus** [comment]
I think the error comes from systemd-boot trying to overwrite the default bootloader, but failing. It seems it succeeded in creating its own boot file though. 

Okay, we should 

1) log bootloader config generation better 
2) display message about successful installation only if it was successful.

**Comment by Onfroygmx** [comment]
Completely agree.
Also what happens if /boot/loader/loader.conf already exist?
With arch it generates a warning, with file already exist.

**Comment by Chrysostomus** [comment]
There might be a warning but the user might not see it. Next step overwrites that file. 

We could try it like this:if systemd-boot is already installed, don't reinstall it, just create new entries. That way it would integrate with already existing installation.

**Comment by Chrysostomus** [comment]
I think this is fixed now
