### ISSUE TITLE
Keymap problem with encrypted root

### ISSUE THREAD

**Issue by Onfroygmx** [Chrysostomus/aif-dev#165]
Major
I installed on a basic lvm/luks partition.
NAME               MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                  8:0    0    10G  0 disk  
|-sda1               8:1    0 488.3M  0 part  /boot
`-sda2               8:2    0   9.5G  0 part  
  `-vgcrypt        254:0    0   9.5G  0 crypt 
    `-vgcrypt-root 254:1    0   9.5G  0 lvm   /
sr0                 11:0    1  1024M  0 rom   

Config files are ok, but my keymap was not correct for unlocking the partition.
The guide I followed had the following mkinitcpio hooks:
HOOKS="base udev autodetect modconf block consolefont keymap keyboard encrypt lvm2 filesystems fsck"
Which worked fine with my arch test install and keymap was respected.

The manjaro install has the following hooks:
HOOKS="base udev autodetect modconf block encrypt filesystems keyboard fsck"
Which did not work as the keymap for unlocking was back to standard US, while after unlocking it was set correctly.

I changed the hooks and run "mkinitcpio -p linux49", rebooted and my keymap was correct for unlocking.

**Comment by Chrysostomus** [comment]
Yes, we should probably add that

**Comment by Chrysostomus** [comment]
This should be fixed now
