### ISSUE TITLE
Review of systemd conf files show all the files in the entries folder

### ISSUE THREAD

**Issue by Onfroygmx** [Chrysostomus/aif-dev#166]
Minor
When selecting review config files after base install, the system loops through all the conf files in the /boot/loader/entries folder.
Even the ones not generated by the installer:
https://cloud.githubusercontent.com/assets/25054585/26265851/11a7dec8-3ce3-11e7-8ac6-05a8214f0981.png
https://cloud.githubusercontent.com/assets/25054585/26265856/19ffaeb6-3ce3-11e7-8406-855515385947.png

**Comment by Chrysostomus** [comment]
This should theoretically be fixed now

**Comment by Onfroygmx** [comment]
And how can it practically be tested?

**Comment by Chrysostomus** [comment]
Before running the function, 

     echo "this file should not come up" > /mnt/boot/loader/test.conf
