### ISSUE TITLE
Add support for partitionless detection and installation

### ISSUE THREAD

**Issue by ghost** [Chrysostomus/aif-dev#169]
Manjaro-architect does not allow me to pick my partitionless BTRFS disk as an install target. Only the USB drive holding Manjaro-architect displays as a valid target. Please add support for partitonless installations.

**Comment by Chrysostomus** [comment]
I'll consider it. Meanwhile you can just mount your device manually to /mnt and continue with the installer. 

Can you post the output of lsblk so I would see how it sees partitionless btrfs volume? The mounting function works by parsing the output of lsblk.

**Comment by ghost** [comment]
I’ll try that now. Here’s a screenshot of lsblk's output: https://goo.gl/photos/Q19FXG2e4MLg7voA9

**Comment by Chrysostomus** [comment]
Thank you. How about 

      lsblk -Ino NAME,TYPE,FSTYPE
? 

I would like to see if we can get btrfs and type at the same line.

**Comment by ghost** [comment]
`lsblk: failed to parse list ‘no’`

**Comment by Chrysostomus** [comment]
lsblk -lno NAME,TYPE,FSTYPE

**Comment by ghost** [comment]
https://goo.gl/photos/noxJQbZiCb6kECwp6

**Comment by Chrysostomus** [comment]
Does not open

**Comment by Chrysostomus** [comment]
Anyway, I was thinking that we could maybe add btrfs disks to the list if it is not too difficult. I have never heard anyone doing partitionless setup with any other file system. Just listing disks among partitions would create too much confusion.

**Comment by ghost** [comment]
The relevant line in the screenshot says `sda disk`.

**Comment by Chrysostomus** [comment]
Thanks, that is enough information.

**Comment by ghost** [comment]
Thanks for taking a look at this. 😊

**Comment by Chrysostomus** [comment]
Btw, is there some secret special benefit for using partitionless btrfs? Isn't it difficult with bootloaders or some thing.

**Comment by ghost** [comment]
It’s a massive pain in the ass basically all of the time for an anecdotal marginal speed boost. I am aware of how ridiculous this is but I can’t stand partitions for purely aesthetic reasons. Also, I’ll take an anecdotal marginal speed boost.

**Comment by ghost** [comment]
GRUB works fine with it. There’s some concern that it is unstable but those concerns appear to be immaterial.

**Comment by ghost** [comment]
Just wanted to thank you again for providing an alternative method to completing this installation.

In a second TTY I mounted my target drive, created a subvolume named manjaro, unmounted, mounted the subvolume then completed the install in the installer on TTY 1. Everything went smoothly, the only issue I had was the installer unmounting my target drive the installer moves into its own partitioning and mounting phase.

Anyway, I now have a partitionless BTRFS installation with NixOS installed to subvolume nixos and Manjaro installed to subvolume manjaro. This makes it extremely easy for me to blow away and recreate any one installation without messing with partitions. And each install resizes dynamically up to my maximum drive space.

Even if you don’t add support for a specifically partitionless setup, you may like to allow users to create and specify a subvolume or subvolumes as targets for a Manjaro install as they are extremely powerful compared to a typical partitioned setup. See here for more:  https://github.com/w0ng/wongdev.com/blob/master/content/pure-btrfs-installation.md

EDIT: Closed issue unintentionally.
