### ISSUE TITLE
Duplicate "Install Custom Packages"

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#170]
This menu entry happens to be in two places now, inside and outside "Install Multimedia Support".

**Comment by Chrysostomus** [comment]
Yes, I figured that it was essential part of custom desktop installation, but buried too deep if someone wanted to use it otherwise. Hence the dublication.

**Comment by oberon-manjaro** [comment]
But why inside the Multimedia menu?

**Comment by Chrysostomus** [comment]
Hmm... Must be a mistake

**Comment by oberon-manjaro** [comment]
That's what I thought ... 😉
