### ISSUE TITLE
Set a theme for rEFInd

### ISSUE THREAD

**Issue by Mauladen** [Chrysostomus/aif-dev#178]
You have a repository with a wonderful theme for rEFInd
When you install Grub with it installed and the theme of Manjaro
Maybe we should do it for rEFInd?

**Comment by Chrysostomus** [comment]
Unfortunately the package for the theme does not work yet, but I was planning on including it once it does.

**Comment by Mauladen** [comment]
Well, it would be cool

**Comment by Chrysostomus** [comment]
Initial version that hardcoded the esp path worked, but it is not an ideal solution. The second version included an install script that determined the esp path at runtime and copied the files there. It put the files in the right place, but for some reason refind did not find them.

**Comment by Chrysostomus** [comment]
Okay, the appropriate package is ready, I'm now looking into this

**Comment by Chrysostomus** [comment]
![adapta-refind](https://user-images.githubusercontent.com/12002226/35321459-a95db7a8-00ef-11e8-9beb-054b36f63862.png)
![lockscreen](https://user-images.githubusercontent.com/12002226/35321460-a983d23a-00ef-11e8-9874-64e4f75fa254.png)
![lxbreth-refind](https://user-images.githubusercontent.com/12002226/35321461-a9a62b96-00ef-11e8-8674-acfc6e807415.png)
![maia-refind](https://user-images.githubusercontent.com/12002226/35321462-a9d1ee16-00ef-11e8-9852-5dbe5cd4a798.png)
