### ISSUE TITLE
The problem with the Zsh configuration in KDE

### ISSUE THREAD

**Issue by Mauladen** [Chrysostomus/aif-dev#180]
![Imgur](http://i.imgur.com/qbIykqm.png)

Why came this "\\\\\\\\\\\\\\\\\\\\\\\\\%"?
In XFCE4 and GNOME, this was not
I didn't touch anything, all out of the box

**Comment by Chrysostomus** [comment]
It was because of a konsole update that made it incompatible with the color scheme setting script

**Comment by Mauladen** [comment]
You'll fix it?

**Comment by Chrysostomus** [comment]
If I can figure out how. The solution is to disable the color script for konsole, but problem is how to know it is konsole (efficiently).

**Comment by Mauladen** [comment]
Yes, you were right and everything is fine in another terminal emulator
I found a workaround for this problem, but of course I would like it to work with the konsole out of the box

**Comment by Chrysostomus** [comment]
What is your workaround? Personally I have considered these options:

1) disable the color script entirely 
- problem: st-manjaro actually needs to set colors with a script. 
2) disable the color script for terminals matching konsoles $TERM 
- problem: konsole uses very common (and misleading) TERM=xterm-256colors, so the fix would also terminals that don't need it. 
3) enable theme colors only for tmux, so st-manjaro gets it.

**Comment by Mauladen** [comment]
@Chrysostomus My solution is very simple, use a different terminal
I think you will find a more effective solution to this problem

**Comment by sanyarnd** [comment]
I appreciate your effort, but zsh setup is broken on KDE (maybe other DE too, I don't know). My keyboard hotkeys doesn't work the way it's in zsh config. I had to remove zsh addition packages and install oh-my-zsh, which works fine out of the box (add few plugins, and here you go).
Can you consider adding oh-my-zsh install + plugins to pair manjaro-based version in further releases?

**Comment by Chrysostomus** [comment]
Nope, mixing plugin framework with settings package is messy (did that with fish). If I used a plugin framework, prezto or zim would be a more likely candidate than oh-my-zsh. 

Which keys did not work?

**Comment by sanyarnd** [comment]
Home/End (dont work), left/right, backspace and some others (work not how described), I don't remember all. 
Could it be because of the keyboard layout? Than it's strange oh-my-zsh works fine out of stock.

**Comment by Chrysostomus** [comment]
Most likely keyboard layout I'll look into how oh-my-zsh does it

**Comment by Chrysostomus** [comment]
What keyboard layout are you using? On my end arrows work with konsole, but home/end does not.

**Comment by sanyarnd** [comment]
They were behaving strange. Inserting special symbols (while holding ctrl). Backspace was working as alt+backspace, removing whole words.
Layout is a4techKB21

**Comment by Chrysostomus** [comment]
What language? How do you set that with setxkbmap?

**Comment by sanyarnd** [comment]
sudo localectl --no-convert set-x11-keymap "us,ru" a4techKB21 "" grp:caps_toggle,terminate:ctrl_alt_bksp
plus locale.conf/locale-gen (did through menus) and vconsole.conf

**Comment by Chrysostomus** [comment]
I can't reproduce unfortunately. I'll retry later. I did some changes to the zshrc that should have fixed the end/home keys. No idea about the backspace. 

https://github.com/Chrysostomus/manjaro-zsh-config/blob/master/.zshrc

**Comment by Chrysostomus** [comment]
Okay, I'm being dense here, but could you further explicate the procedure? When I tried that localectl command on installed system I just got errors. And with manjaro-architect I could not find that layout, or anything similar to it.

**Comment by sanyarnd** [comment]
I've been using manjaro-achitect setup. Manjaro architect didnt work from ISO, so I've used manjaro live-USB with installed manjaro-architect package.
I've installed english version (Manjaro still doesn't properly install dual language support), with minimal KDE, systemd and zsh.
The next thing I did was turning wallet system off, and then going through every language menu.
Here's the basic installation guide I've been using: [link](https://wiki.archlinux.org/index.php/Internationalization_(%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9))
Since SDDM uses X11 layout, I had to execute 
```
sudo localectl --no-convert set-x11-keymap "us,ru" a4techKB21 "" grp:caps_toggle,terminate:ctrl_alt_bksp
```
where --no-convert basically means it won't touch /etc/vconsole.conf, otherwise it'll override settings I've made, everything else is straightforward.
Also I've checked that /etc/locale.conf contains only one language (LANG=ru_RU.UTF-8), because setting things from menus can fuck up locale.conf, and it'll contain something lile:
> LANG=ru_RU.UTF-8
> LANGUAGE=en_US.UTF-8

and it screws SDDM look.

**Comment by Chrysostomus** [comment]
Thanks. Installing kde now to test, since gnome overrides those alues with its own settings...

**Comment by sanyarnd** [comment]
I forgot to add, that even I have one language in /etc/locale.conf, I have 2 locales enabled in menus: some Java apps w/o localization are confused if en_** is not present.

Here's the command log:
```
➜  ~ localectl       
   System Locale: LANG=ru_RU.UTF-8
       VC Keymap: us
      X11 Layout: us,ru
       X11 Model: a4techKB21
     X11 Options: grp:caps_toggle,terminate:ctrl_alt_bksp
➜  ~ locale -a
C
en_US.utf8
POSIX
ru_RU.utf8
```

**Comment by Chrysostomus** [comment]
Okay, I installed plasma desktop, set locale to russian and set keyboard like you did. Still cannot reproduce, maybe it is something other than the locale then. 

Have you tried the updated zshrc?

**Comment by Chrysostomus** [comment]
Oh wait, now I can... the backspace works, but arrows and home/end produce letters instead....

**Comment by Chrysostomus** [comment]
Now it somehow magically disappeared again. It seems to be somehow tied to caps lock...

**Comment by sanyarnd** [comment]
So your suggesting it's broken because of caps lock keyboard switching? I have it right now, but oh my zsh handles it. On the other hand, oh my zsh was installed after I've selected caps lock as a switch combination.

**Comment by Chrysostomus** [comment]
No, I have no idea what causes it. But suddenly after I ran a single bindkey command manually, all broken keys started to work.
