### ISSUE TITLE
Error [set_xkbmap se][1]

### ISSUE THREAD

**Issue by methuselah-0** [Chrysostomus/aif-dev#181]
Got that error in "Set Desktop Keyboard Layout" of "Configure Base" when installing manjaro 17.0.2-stable-x86_64 with v0.8.13 Manjaro Architect Installer.

If set_xkbmap se is the issued command then it just needs changed to setxkbmap se I think.

**Comment by Chrysostomus** [comment]
It is not the issued command but the nape of the called function. Specifically this:

```
set_xkbmap() {
    XKBMAP_LIST=""
    keymaps_xkb=("af al am at az ba bd be bg br bt bw by ca cd ch cm cn cz de dk ee es et eu fi fo fr\
      gb ge gh gn gr hr hu ie il in iq ir is it jp ke kg kh kr kz la lk lt lv ma md me mk ml mm mn mt mv\
      ng nl no np pc ph pk pl pt ro rs ru se si sk sn sy tg th tj tm tr tw tz ua us uz vn za")

    for i in ${keymaps_xkb}; do
        XKBMAP_LIST="${XKBMAP_LIST} ${i} -"
    done

    DIALOG " $_PrepKBLayout " --menu "\n$_XkbmapBody\n " 0 0 16 ${XKBMAP_LIST} 2>${ANSWER} || return 0
    XKBMAP=$(cat ${ANSWER} |sed 's/_.*//')
    echo -e "Section "\"InputClass"\"\nIdentifier "\"system-keyboard"\"\nMatchIsKeyboard "\"on"\"\nOption "\"XkbLayout"\" "\"${XKBMAP}"\"\nEndSection" \
      > ${MOUNTPOINT}/etc/X11/xorg.conf.d/00-keyboard.conf 2>$ERR
    check_for_error "$FUNCNAME ${XKBMAP}" "$?"
}
```

I'll look into it some day when I have the time. Could you post your install log?

**Comment by methuselah-0** [comment]
Sure.
[log](http://sprunge.us/biFM)

**Comment by oberon-manjaro** [comment]
Not much to tell from the log unfortunately...
Was the file **/etc/X11/xorg.conf.d/00-keyboard.conf** created in the target at all?

**Comment by methuselah-0** [comment]
> Was the file /etc/X11/xorg.conf.d/00-keyboard.conf created in the target at all?

No.

**Comment by oberon-manjaro** [comment]
And the keymap entry you selected was plain `se`?
Do you still have the possibilty to remount the same install in a live environment or chroot of any kind and then try executing this (in the host) and see what the output is:
```
echo -e "Section "\"InputClass"\"\nIdentifier "\"system-keyboard"\"\nMatchIsKeyboard "\"on"\"\nOption "\"XkbLayout"\" "\"se"\"\nEndSection" \
      > /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
```

**Comment by Chrysostomus** [comment]
Does the issue persist?

**Comment by methuselah-0** [comment]
Hi, can't say if it exists still, haven't tried again for a very long time.
