### ISSUE TITLE
Set enviroment vars $EDITOR and $VISUAL to some text editor like nano

### ISSUE THREAD

**Issue by wilfred1986** [Chrysostomus/aif-dev#182]
On every installation of manjaro I made, this is always I have to do in /etc/enviroment

It will be nice if the architect installer could do it.

Thanks for your work! :)

**Comment by Chrysostomus** [comment]
It should be done at iso-profile level in my opinion. I usually do it in ~/.profile. 

I agree that it is problematic when these values are not set.
