### ISSUE TITLE
Can't install an unconfigured desktop environment

### ISSUE THREAD

**Issue by tenten8401** [Chrysostomus/aif-dev#185]
When using the Manjaro architect ISO, I can't install an unconfigured desktop environment. When clicking it, it says something about install vanilla de wm not found for a split second and just skips to the next option.
Managed to snag a picture of it: http://i.imgur.com/fRQJ1mJ.jpg

**Comment by Chrysostomus** [comment]
Fixed now in #76e08a7

**Comment by tenten8401** [comment]
Going to test this out right now. Thanks!

**Comment by tenten8401** [comment]
Cloned from git and installed with makepkg. This has not been fixed.

**Comment by tenten8401** [comment]
Actually, could the script be updating itself from the repositories rather than using the git version? Going to look into that now.

**Comment by Chrysostomus** [comment]
Try the version in manjaro unstable repos now. I suspect that the you used the PKGBUILD that builds fixed release. The PKGBUILD for manjaro-architect-dev builds the latest git version. https://github.com/manjaro/packages-community/tree/master/manjaro-architect-dev

But the version in repos should work. 0.8.17.
