### ISSUE TITLE
Where can I get the Server-Profile

### ISSUE THREAD

**Issue by mac-linux-free** [Chrysostomus/aif-dev#202]
like the old manjaro-net installer..please

**Comment by Chrysostomus** [comment]
What is that? Tell me more and I'm happy to help.

**Comment by mac-linux-free** [comment]
I simply need an option to just install a base-system with networkmanager, openssh, samba, docker, etc.

as reference there is arch-anywhere-installer or to old manjaro-net-0.8.6 installer

could you do that with an seperate iso-profile ?

**Comment by Chrysostomus** [comment]
Yes, it is possible. If someone adds a server profile to this repo:

https://github.com/manjaro/iso-profiles/

It automatically becomes available in manjaro-architect. You can open an issue there or start a thread in manjaro forums in development section to get someone to do it. Manjaro arm had pre-configured isos for servers, so Strit might know something about this.

**Comment by mac-linux-free** [comment]
oh cool, there is already the netinstall-profile...didn't find it in the architect installer

**Comment by Chrysostomus** [comment]
That's because netinstall profile would produce exactly the same result as just installing base. That netinstall is what you get when you install base with manjaro architect.

**Comment by Chrysostomus** [comment]
But you can also add networkmanager and samba under the advanced section, in the unconfigured desktops menu. 

Still, it would be nice to have a separate server profile.

**Comment by mac-linux-free** [comment]
ok thank you
