### ISSUE TITLE
extra package selection has no apparent exit

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#209]
With the latest way of installing a Manjaro Desktop, after having selected a profile, immediately this screen pops up:
![screenshot_2017-08-17_16-12-51](https://user-images.githubusercontent.com/11800714/29416672-2a19c154-8367-11e7-850f-4548cb0eeadc.png)

There's no apparent way or explanation visible for how to close it (I think it's probably in the cut off text?).
Also I think it's not ideal that the extra package selection just pops up without any announcement or that you had intentionally asked for it.

**Comment by Chrysostomus** [comment]
Okay. We need at least make text visible in smaller terminals, and perhaps also add dialog to ask if user wants something extra?

**Comment by Chrysostomus** [comment]
Okay, there is now a dialog asking if user wants some extras. And the header message of package selection is now on multiple lines to ensure visibility of instructions.
