### ISSUE TITLE
deselect all extramodules by default?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#210]
Currently headers, ndiswrapper and acpi-call are preselected.
Most users won't need any of the three I think. Especially ndiswrapper, which is about to be removed from extramodules anyway in the near future. ...
I would suggest to deselect everything by default and leave it to the user to install what they might need.

**Comment by Chrysostomus** [comment]
I'm okay with it. Alternatively, preselect the modules that are currently loaded? I think mhwd does something like that?

**Comment by oberon-manjaro** [comment]
That sounds like a great idea. Any idea how to achieve that?

**Comment by Chrysostomus** [comment]
Yes

**Comment by Chrysostomus** [comment]
I think that the live media script had a snippet of code that did that. I ran into it when I was trying to figure out how mhwd detects right modules. I concluded that it didn't, it just used whatever the live media had loaded.

**Comment by Chrysostomus** [comment]
And once we figure out that, it is a simple matter of sed or for loop.

**Comment by Chrysostomus** [comment]
The modules are now deselected by default
