### ISSUE TITLE
menu position of 'Chroot into installation'

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#211]
Atm this entry is placed inside 'Install Desktop System' menu. I'm not convinced this is a good place - certainly not where you would intuitively look for it...?
I would suggest to place it in the Main Menu under 'Install Custom System'.
What do you think?

**Comment by Chrysostomus** [comment]
? The three menus are meant to be mutually exclusive and they all include the chroot option. It is equally useful for each installation type. 

Once we implement the tweaks submenu, maybe place chroot option there?

**Comment by oberon-manjaro** [comment]
The usecase I was thinking of is that you have a problem with an existing install and you want to use the MA-ISO to fix it.
When I launch m-a I would just expect to have the rescue option in the main menu, since I'm not about to use any of the installation options ...

**Comment by Chrysostomus** [comment]
Aa. That is certainly a possible use, although not what I had in mind. The use case I had in mind was tweaking and doing postinstallation stuff. 

I see a few possible options:

A) leave things as they are, the option is really easy to find if you are looking for it. 
B) remove the option from all installation types and put it as fith option in top level menu. 
C) keep chroot option in all installation types, but also create a system rescue option in the top level menu. It would contain maybe 

- chroot 
- bootloader installation 
- driver installation 
- add/remove packages from target 
- update target 
- enable/disable services from target 
- display system info 
- view logs (pacman, systemd etc) 
- try to fix pacman errors 

Which option would you find interesting?

**Comment by oberon-manjaro** [comment]
I like **C** a lot. Nice idea! **A** doesn't convince me personally so much.
**B** would also be ok.

**Comment by Chrysostomus** [comment]
Okay. Let's do c then. I'll do the easy parts and then add later more difficult options.

**Comment by oberon-manjaro** [comment]
Great!

**Comment by Chrysostomus** [comment]
Okay, there is now a rudimentary rescue menu:

![screenshot from 2017-08-18 00-46-48](https://user-images.githubusercontent.com/12002226/29435222-cecbb008-83ae-11e7-9056-a0821fd080ba.png)

We can probably work from there.

**Comment by oberon-manjaro** [comment]
Looking great!
I'd suggest to have a copy of 'Mount Partitions' inside 'System Rescue' - so it becomes independent from the other menus, if you agree?

**Comment by oberon-manjaro** [comment]
I just tried this quickly in a vbox.
Somehow the 'fg' command to return to the installer doesn't seem to work:

![fg_no_such_job](https://user-images.githubusercontent.com/11800714/29444724-38937c90-83e2-11e7-9b77-25c056cc6f04.png)

**Comment by Chrysostomus** [comment]
It seems you did not exit the chroot first

**Comment by Chrysostomus** [comment]
I don't know about adding mount menu to system rescue. It is possible. 

I was thinking we could add some kind of automatic mount option, and generally improve mounting of pre-existing partitions, especially with btrfs subvolumes. We could then trigger the automatic mounting if user tries to start system rescue menu without mounting partitions. Just take some code from manjaro-chroot and improve it to account for btrfs subvolumes.

**Comment by oberon-manjaro** [comment]
ah I see, sorry ;)
After typing exit it looked like m-a had quit.
Sounds good about the auto-mounting 👍

**Comment by Chrysostomus** [comment]
Btw, can you think of a way to automatically return to installer when chroot ends?

**Comment by oberon-manjaro** [comment]
Hm, I don't know. Trapping similar to what we do with update keys apparently doesn't seem to work here...?
