### ISSUE TITLE
No Os-prober

### ISSUE THREAD

**Issue by mhham** [Chrysostomus/aif-dev#218]
The option to use GRUB and `os-prober` is not present (install made in september 2017).

**Comment by Chrysostomus** [comment]
Is this uefi or legacy? In uefi os-prober is included by default.

**Comment by mhham** [comment]
This is UEFI, and I had to manually chainload my windows partition after install

**Comment by Chrysostomus** [comment]
Thank you, I'm looking into the issue.

**Comment by mhham** [comment]
Thinking of it again, this issue could come from the fact that I mount the EFI partition on /boot/efi  (the default option in the installer) instead of /boot.
Hence `update-grub` which is just an alias for `grub-mkconfig -o /boot/grub/grub.cfg` does not change my real grub configuration file, which is in `/boot/efi/grub/grub.cfg`

Overall, it seems that mounting the EFI partition in /boot/efi only causes problems with encrypted setups ...

**Comment by Chrysostomus** [comment]
No, that's not it. Update-grub works with /boot/efi esp.

**Comment by mhham** [comment]
> No, that's not it. Update-grub works with /boot/efi esp.

That's weird.. Currently on my device with /boot/efi esp I had a lot of issues after kernel update. Had to manually copy linux images from /boot to /boot/efi, and grub.cfg generated by update-grub was completely messed up, due to /boot being encrypted (as it is part of the root volume which is the LUKS partition) and /boot/efi not.

Frpm my experience, everything should work fine on a non encrypted setup with /boot/efi esp, however on an encrypted setup the *unencrypted* esp should be on /boot.

**Comment by Chrysostomus** [comment]
You should have (but probably don't, because installer did not recognize Luks with lvm on top of it) this line in /etc/default/grub:

    GRUB_ENABLE_CRYPTODISK=y

Run update-grub after adding that. This required for having initramfs and kernels on encrypted partiton.

**Comment by mhham** [comment]
> You should have (but probably don't, because installer did not recognize Luks with lvm on top of it) this line in /etc/default/grub:
> 
> GRUB_ENABLE_CRYPTODISK=y
> 
> Run update-grub after adding that. This required for having initramfs and kernels on encrypted partiton.

This is true, but since I don't care about having an encrypted /boot partition, and don't want to type my password twice, I ended up changing the mount point of the unencrypted EFI partition from /boot/efi to /boot. My multiple update-grub related problems are now history :)

cf other [issue](https://github.com/Chrysostomus/manjaro-architect/issues/217#issuecomment-333569673)

Also, os-prober works correctly now
