### ISSUE TITLE
[Appearance] Change default background color for tty

### ISSUE THREAD

**Issue by mhham** [Chrysostomus/aif-dev#219]
It is currently dark-gray, it would be nice to have the possibility to change it to another color (black for instance)

**Comment by Chrysostomus** [comment]
Are you meaning the manjaro-architect iso, or something else? The gray background is provided by the package maia-console. You can remove that if you got an edition including it, or alternatively edit the files owned by it to change the colors.

**Comment by mhham** [comment]
Ok, good to know, I will try this and keep you posted

**Comment by mhham** [comment]
Deleting maia-console worked as a charm! Thanks !
