### ISSUE TITLE
installation and settings need to be ckecked before the installer quits

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#22]
The installer should not just quit without complaining if something essential has been forgotten, like for example right now you can just quit after installing base and a DE but without installing a bootloader (ok, might make sense) or without having created a user or installing a video-driver ...
It's quite annoying if you have forgotten something and you have to start over again with installing base and so on. You should be warned at least in that case.

**Comment by Chrysostomus** [comment]
Yeah, warning might be good. I would not prevent quitting though, because it can be useful.

Why would you start over from beginning though? Just mount the partitions without formatting and continue from where you left?

**Comment by Chrysostomus** [comment]
I wonder if there is a way to make some kind of checklist in the main menu. Just having mention in the exit menu would be easier to code though.

Are you sure you want to quit?
You have not installed the base.
You have not installed the bootloader.
You did not install any graphical environment.

**Comment by Chrysostomus** [comment]
Root has no password
you did not crate any users
fstab was not generated

**Comment by oberon-manjaro** [comment]
> Why would you start over from beginning though?

When I try that **m-a** will not allow me to install a DE directly. It demands to install base first. Maybe that's also something to reconsider ;)

**Comment by Chrysostomus** [comment]
Weird. For me it recognizes the already installed base.

**Comment by oberon-manjaro** [comment]
Is it possible that I destroyed the existing base install by just having it mounted as ext4??
It says "IMPORTANT: Partitions can be mounted without formatting them by selecting the "SKIP / NONE" option" If that really means that an existing parition is destroyed at that point we'd definitely add another warning during mount!

**Comment by Chrysostomus** [comment]
It is possible, but if you chose skip/none then it was not formatted. Skip/none does not format, everything else does.

**Comment by Chrysostomus** [comment]
But how would we check if warning is needed?

**Comment by oberon-manjaro** [comment]
I'll think about it and will propose something... - need to dive into the code a little more still ... :wink:

**Comment by oberon-manjaro** [comment]
I just added it to the existing feedback :smiley: 

![](http://imgur.com/UvycAY0.png)  :warning:

**Comment by Chrysostomus** [comment]
Nice. Informative and unintrusive.

**Comment by Chrysostomus** [comment]
We should also check if locales have been generated. Failure to do so breaks stuff like tmux.

**Comment by Chrysostomus** [comment]
Things to check:
1) base
2) bootloader 
3) mkinitcpio
4) root password 
5) users
6) locales
7) fstab

**Comment by oberon-manjaro** [comment]
Also we should clean up all those temp files ... :wink:

**Comment by Chrysostomus** [comment]
I started to write the final check:

```
final_check()
{
    # Empty the list
    echo "" > ${CHECKLIST}
    # Check if base is installed
    [[ -e /mnt/etc ]] || echo "- Base is not installed" >> ${CHECKLIST}
    # Check if bootloader is installed
    [[ -e /mnt/etc ]] || echo "- Bootloader is not installed" >> ${CHECKLIST}
    # Check if fstab is generated
    [[ -e /mnt/etc/fstab ]] || echo "- Fstab has not been generated" >> ${CHECKLIST}
    # Check if locales have been generated
    [[ ]] || echo "- Locales have not been generated" >> ${CHECKLIST}
    # Check if root password has been set
    $(grep -q -e 'root:!:' -e 'root:\*:' /mnt/etc/shadow) || echo "- Root password is not set" >> ${CHECKLIST}
    # check if user account has been generated
    [[ $(ls /mnt/home) == "" ]] || echo "- No user accounts have been generated" >> ${CHECKLIST}
}
```

What would be good way to check if locales have been generated?

**Comment by Chrysostomus** [comment]
My idea is: When quitting installer, if ${CHECKLIST} is not empty, display it as a part of the "Close installer?"-dialog

**Comment by Chrysostomus** [comment]
There is now rudimentary final_check function implemented

**Comment by oberon-manjaro** [comment]
quite satisfying for now I would say :)

**Comment by oberon-manjaro** [comment]
Should we also check if a video-driver has been installed - since it will leave the target unbootable to desktop if not?

**Comment by oberon-manjaro** [comment]
Any idea how we could do that? Do we need to touch another marker file in /mnt ?
I can't think of a way how to grep output of ``mhwd -li`` in a helpful way... ?

**Comment by Chrysostomus** [comment]
I don't know, there are also valid reasons for not installing any driver... Need to look into It further

**Comment by oberon-manjaro** [comment]
Sure you might want to install no video-driver. You'd will simply confirm when the installer exits.
The concern is more that you might have missed to install one when you wanted to :wink: 
touching a **/mnt/.video_installed** or so will work of course, although - like our **.base_installed** will not guarantee that installation was successful. But it would at least be some kind of a reminder and effictive in most cases.
Not perfect - but not too bad?

**Comment by Chrysostomus** [comment]
Touch it only if mhwd command is successful? & &

**Comment by oberon-manjaro** [comment]
yes. something like that.

**Comment by oberon-manjaro** [comment]
I've just added it after the check_for_error functions, so nothing should be touched when error check aborts.
Added to final check now.
