### ISSUE TITLE
Add support for keyfiles in luks setup

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#222]
I just tested setting a keyfile in initramfs, worked pretty nicely. As a next project, I would like to have

1) option to add keyfile in LUKS setup
2) If using grub with encrypted /boot, automatically setup keyfile and embed it in initramfs, so that user needs to input their password only once.

**Comment by Chrysostomus** [comment]
Initial support now added for encrypted /boot and grub.

**Comment by runningman84** [comment]
If there is a keyfile added to the initramfs how secure is the whole system? Isn't the initramfs stored unencrypted?

**Comment by Chrysostomus** [comment]
Initramfs is stored on /boot. With encrypted /boot, it is pretty much safe. Without encrypted /boot, it renders the whole encryption pointless. Current setup only generates keyfile when /boot is encrypted and grub is used.

**Comment by runningman84** [comment]
Great. If you are already looking into this whole Luks setup it would be cool if you make clear what combination of partition layout, filesystem and boot loader work together.

**Comment by bilkoua** [comment]
How is it possible to test it? Can you make some instruction?

**Comment by Chrysostomus** [comment]
https://forum.manjaro.org/t/testing-needed-for-manjaro-architect/37422/7

For the best results, install this PKGBUILD with makepkg -sric 

https://github.com/manjaro/packages-community/tree/master/manjaro-architect-dev

**Comment by bilkoua** [comment]
I think will be better make dev iso for more simple test for most people and it would help find more testers.

**Comment by Chrysostomus** [comment]
point taken.
