### ISSUE TITLE
Target not found: manjaro-gdm-check while choosing GNOME

### ISSUE THREAD

**Issue by flymia** [Chrysostomus/aif-dev#224]
While choosing GNOME in the installation process, the installer fails with the following error:

`install basepkgs[255]`

When pressing enter afterwards, following message shows up:

`errror: target not found: manjaro-gdm-check`
`==> ERROR: Failed to install packages to new root`

I am using the latest verson of the manjaro-architect from SourceForge.

**Comment by Chrysostomus** [comment]
Someone has added an package that is not yet in all branches. You can

A) Wait until it gets to the stable branch (within 2 weeks) 
B) use unstable branch 
C) remove the package from the installation list. When installer asks if you want to add custom packages, edit in another terminal 

        sudo nano /mnt/.{base,desktop}
and remove that package from the list.
