### ISSUE TITLE
Canot mount hdd partitions

### ISSUE THREAD

**Issue by kuba-orlik** [Chrysostomus/aif-dev#225]
After picking "Mount partitions", only the `/dev/sdb` partition shows up (and it represents the USB stick that I'm running the Architect from), so I have no way to preceed :(

**Comment by Chrysostomus** [comment]
What is the output of

      lsblk

**Comment by kuba-orlik** [comment]
I've managed to solve this by repartitioning and removing old luks partition signatures, probably wasn't Architect's fault ;)
