### ISSUE TITLE
Redundant 'GRUB_ENABLE_CRYPTODISK=y' in `/etc/default/grub`

### ISSUE THREAD

**Issue by kuba-orlik** [Chrysostomus/aif-dev#226]
My installation scenario involved creating an unecrypted /boot partition, and luks-encrypted partition for everything else.

When I booted the system, it asked me for the LUKS password before GRUB - and decrypting took about a minute! Then GRUB showed up, and after picking the system I was asked for the password once more. So all in all I had to enter the password twice and the first decryption was very slow.

I searched around and found out that commenting out the `GRUB_ENABLE_CRYPTODISK=y` line in `/etc/default/grub` helped - no I only need to enter the LUKS password *after* GRUB, and the whole boot process is faster.

I think it would be a good idea to comment out this line if it's not necessary, to speed up boot time for this installation scenario

**Comment by Chrysostomus** [comment]
Does this happen with the latest git version? It should have been fixed in 830b007c8eec6afb42638488a8bbbe0d4eff3a2e on october 27. I now tried again with f39f90d84953e48c337b74109b2fa5b6823299db

**Comment by bilkoua** [comment]
with latest version (installation step update scripts from git) we can have 3 times `GRUB_ENABLE_CRYPTODISK=y` in `/etc/default/grub`
mb need use 
`if ! (( $(grep -c "GRUB_ENABLE_CRYPTODISK=y" /mnt/etc/default/grub) == 0 )) ; then echo "GRUB_ENABLE_CRYPTODISK=y" >> /mnt/etc/default/grub; fi` 
instead 
`echo "GRUB_ENABLE_CRYPTODISK=y" >> /mnt/etc/default/grub`

**Comment by Chrysostomus** [comment]
Added yesterday

**Comment by bilkoua** [comment]
Not right and me understand why we have duplicate. Without verification availability `GRUB_ENABLE_CRYPTODISK=y` in `/etc/default/grub` and second using options"install bootloader" (if first was failed) script create duplicate `GRUB_ENABLE_CRYPTODISK=y`.
Install bootloader can be fail if don't mount /mnt/boot or /mnt/boot/efi (as in this issue - https://github.com/Chrysostomus/manjaro-architect/issues/228)

**Comment by Chrysostomus** [comment]
Fixed in 083a91c198fb9561e5c5b420ebe8f0951360f495
