### ISSUE TITLE
Extra Packages - Full vs Minimal?

### ISSUE THREAD

**Issue by polarathene** [Chrysostomus/aif-dev#227]
There isn't any description of what full vs minimal involves in the packages. I'm having difficulty finding out via google as well what the difference is. Could this be documented somewhere, I noticed this project has no Wiki content presently. 

Which one is more like the official Manjaro versions?(Full? If so what sort of things do you lose by going with minimal? Yes I'm aware I could add them later, just not sure how many packages in difference we're talking about, or rough filesize difference).

**Comment by Chrysostomus** [comment]
The difference is that the minimal installation includes the packages tagged with >basic, full includes the packages tagged with >extra. See here for an example:

https://github.com/manjaro/iso-profiles/blob/master/manjaro/kde/Packages-Desktop

Minimal version are used for the testing releases, and the full versions are used for the actual releases. For example, full gnome edition includes printing support, minimal does not. Full kde version uses Firefox and has many themes included, the minimal has one theme and uses qupzilla.

This kind of differences

**Comment by polarathene** [comment]
Thanks, that was helpful :)

**Comment by CyborTronik** [comment]
After so  many years, still the same issue. Could you please add a little description on the download page?
Why I do have to search on internet about such small info?
2023 searching a question from 2017.
Thanks

**Comment by Chrysostomus** [comment]
What download page are you talking about? If you are referring to manjaro.org/download, this repo has nothing to do with it. Also, this repo is achieved, the development has moved to gitlab. I suggest you ask codesardine about it in telegram or in the forum.
