### ISSUE TITLE
Install of XFCE fails - no target for manjaro-xfce-gtk3-settings

### ISSUE THREAD

**Issue by barryspearce** [Chrysostomus/aif-dev#239]
Latest version of Manjaro architect on fully up to date system.
Fails to install Manjaro Desktop with xfce full chosen. 
An Error dialog is display stating [install basepkgs][255]
Originating error was:
Error: target not found: manjaro-xfce-gtk3-settings.

The package no longer seems to exist.
Pacman -Ss manjaro-xfce-gtk3-settings
returns no matches.

This is a significant error which means it is not possible to install any Manjaro XFCE systems from manjaro-architect.

**Comment by Chrysostomus** [comment]
Someone needs to update the xfce git profile. It will work again soon

**Comment by oberon-manjaro** [comment]
The **manjaro-xfce-gtk3** package hasn't been forwarded to stable branch, yet. So currently the xfce profile, which is already at pre-18.0 state, can only be built against unstable or testing branches.

**Comment by oberon-manjaro** [comment]
@philmmanjaro can we forward the gtk3-settings pkg to stable branch so xfce can again be installed with architect?

**Comment by hphilm** [comment]
Well, it can be forwarded ...

**Comment by oberon-manjaro** [comment]
Yep. Done already :-)
