### ISSUE TITLE
additional pkgs full/minimal ??

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#240]
I am currently updating the tutorial and stumbled upon a strange dialog.
After I have selected a Manjaro Desktop I arrive at the 'additional packages' selection, then after selecting 'no' I get this:

![screenshot_2018-04-06_20-12-11](https://user-images.githubusercontent.com/11800714/38437253-2ed8379e-39d7-11e8-9050-6c3339888295.png)

Is it just the header that is wrong?

**Comment by Chrysostomus** [comment]
Seems so. Wrong message.

**Comment by oberon-manjaro** [comment]
Here's this problem :stuck_out_tongue_winking_eye: 
```
$ grep -re "_ExtraBody" .
./data/translations/english.trans:_ExtraBody="This edition is offered in two versions"
./data/translations/english.trans:_ExtraBody="Would you like to add any additional packages to your installation?"
```

**Comment by oberon-manjaro** [comment]
Same for
```
./data/translations/english.trans:_ExtraTitle="Full or minimal?"
./data/translations/english.trans:_ExtraTitle="Extra Packages"
```

**Comment by oberon-manjaro** [comment]
So we need two new strings like `_ExtraPkgTitle` and `_ExtraPkgBody` vs `_ExtraTilte` and `_ExtraBody` and add them to all translation files...

**Comment by Chrysostomus** [comment]
Unfortunately this seems to be the case

**Comment by oberon-manjaro** [comment]
Well, actually they simply need to be renamed in the respective places :)

**Comment by oberon-manjaro** [comment]
I can do that later today most likely ...
