### ISSUE TITLE
release ?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#241]
Just fixed some little bug with language files and headers.
Now since we have arrived at latest release **0.9.9** what do we do?
Ready for **m-a 1.0** ? Or rather a shy **0.9.9.1**? :wink:

**Comment by Chrysostomus** [comment]
0.9.10 :slight_smile:

**Comment by Chrysostomus** [comment]
1.0 still has some issues before it can be released, like broken hibernation support and so on.

**Comment by oberon-manjaro** [comment]
> 0.9.10 :slight_smile:

Right! Somehow I didn't come up with that one! :rofl:
