### ISSUE TITLE
Import to Manjaro GitLab

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#246]
Hi @Chrysostomus 
I have imported this repo to Manjaro's GitLab and configured Master rights for you.
If you like development of manjaro-architect can be continued there completely.

**Comment by oberon-manjaro** [comment]
The complete issues and git history have been copied over to the new instance
https://gitlab.manjaro.org/applications/manjaro-architect

**Comment by Chrysostomus** [comment]
Excellent!

**Comment by mskiptr** [comment]
@Chrysostomus @oberon-manjaro 
Does it mean all the issues should be filed there? I have a few bug reports | feature requests that I wanted to submit, so I'd like to know where is the right place.
Also if that is the case, could you update the readme to inform others?

**Comment by mskiptr** [comment]
Well, here is a PR doing this: https://github.com/Chrysostomus/manjaro-architect/pull/264
I guess there's no one here to even accept this. So I'm going to the gitlab
