### ISSUE TITLE
255 Error

### ISSUE THREAD

**Issue by Yaksinikos** [Chrysostomus/aif-dev#255]
For the last few days, after the update on 04 April 19 sarchitect is giving "error 255 basepkgs" on any kind of installation,
CLI, desktop and various kernels.
Just try yourself.

Been trying it now for days ... Now writing from mobile phone :D

Issue is approved by two persons in the manjaro telegram chat, forum and myself tried it on VM and on real hardware.

**Comment by Chrysostomus** [comment]
I have done test installs and have not met the issue. 255 is almost always specific to the the iso profile. What desktop did you have the issue with?

**Comment by Yaksinikos** [comment]
> I have done test installs and have not met the issue. 255 is almost always specific to the the iso profile. What desktop did you have the issue with?

hmm, I've tried the 
MATE 18.0.1, BSPwm 18.0.4 as well as KDE 18.0.1 ISO.
Architect v0.9.22
Simple basic installation with Kernel 5.0 or 4.19 and no extra modules.
CLI or Mate minimal setup.
Do not work on Hardware or even in VM.
Gives instant a Error 225 on installing the base. 

Give me 30 Minutes, I will try it again, maybe this error just came from outdaten repos, but not sure - because I tried it since 11'o clock of the 4. April.

**Comment by Chrysostomus** [comment]
It doesn't matter which iso is used, only which desktop is chosen at the installation time. That is what determines the package list. Also, it would be super helpful if you can scroll up and check which package is causing the issue.

I'll do some tests in the evening

**Comment by Yaksinikos** [comment]
Edit: its Architect v. 0.9.22

And no, do not work either.
Just downloaded the kde iso for Oracle VM, skipped all configurations, mounted root.
Took Kernel 5.0 & MATE desktop, instant error 255.

It gives warnings on 3 providers for pamac as well as
"==> ERROR: Failed to install packages to new root".

But, I tested it now on three different hard-drives and in VM ware on virtual drives.
Also a other dude tested it and it is not a hard-drive error!

**Comment by Chrysostomus** [comment]
I did not think it was, hardware doesn't cause this issue. There are some dysfunctional iso-profiles (or outdated repos), I just need to find which ones are not working. It sounds like this is caused by pamac being renamed. I'll look into it today

**Comment by Yaksinikos** [comment]
> I did not think it was, hardware doesn't cause this issue. There are some dysfunctional iso-profiles (or outdated repos), I just need to find which ones are not working. It sounds like this is caused by pamac being renamed. I'll look into it today

Thank you.
If you'r trying, could you look for Mate desktop as well, because they did something with the packages of mate in the last updates. (see change-log).

Thanks again!

Edit (7. Aprl. 19);
Looks like this was a issue of repos. Todays update fixed it for my VM test-installation.
I'll try it later on my Hardware.
