### ISSUE TITLE
Can not boot after installation

### ISSUE THREAD

**Issue by kitepad** [Chrysostomus/aif-dev#260]
OS : Win 10 Enterprise 1909
VirtualBox: 6.1.2 with extension
Manjaro Architect : 18.1.0 or architect installer within 18.1.5 XFCE

**Comment by Chrysostomus** [comment]
Unfortunately this is not enough information to help you. Where does it stop when trying to boot? Do you get to the bootloader, initramfs or tty stage? What exactly happens? What is your partition layout? Which bootloader and which desktop you chose? Which graphics card?

If you have a specific bug you want to report, you can do it here (or preferably in gitlab where the repo has been moved). If you need advice and technical assistance, you will probably get help quicker in forum.manjaro.org.

**Comment by kitepad** [comment]
Installed CLI system can not boot, but launch live cd installer to install xfce desktop, os can boot successfully.

My install steps for your information:
1. Download Manjaro XFCE edition x86-64, 18.1.5.
2. Install VirtualBox 6.1.2 on Win 10.
3. Create new vm with vb default setting (4096 mem, 12gb hd, 128M video mem)
4. Boot vm by live cd
5. Launch Manjaro Architect to go select english->us->time zone-> install CLI system ->select basic with linux55->kernel header->install bootloader->select grub->configure fstab, account->done

**Comment by papajoker** [comment]
iso MA is old with pacman 5.1 (pacman 5.1 can't create a good boot  - kernel kooks break)
update to pacman 5.2 before install

OR
use manjaro-architect from an other iso with pacman good version (gnome, xfce, kde)

**Comment by oberon-manjaro** [comment]
> iso MA is old with pacman 5.1

Actually latest architect-ISO 18.1.5 is just 3 days old and includes pacman 5.2.1-4 ... :wink: 
https://osdn.net/projects/manjaro/storage/architect/18.1.5/
Anyway, OP apparently used latest xfce ISO for installation.

**Comment by kitepad** [comment]
Download and try latest architect-iso 18.1.5, all of problems are gone.😉
Thanks for your support.
