### ISSUE TITLE
Adding a swapfile isn't an option

### ISSUE THREAD

**Issue by Nova-Aurora** [Chrysostomus/aif-dev#263]
According to the documentation, adding a swapfile should be given as an option when mounting, however, I only get the chance to make a physical swap partition, with it mentioning, but not giving me the option for, a swapfile. The filesystem is btrfs with compress-zstd, nossd. Is this a pebkac?

**Comment by Chrysostomus** [comment]
Swapfile creation is disabled for btrfs because we ship kernels that don't support swapfiles on btrfs. Also, proper swapfile support for btrfs would require a separate subvolume for it with cow disabled.

**Comment by Nova-Aurora** [comment]
Ok. I guess that is one of the things about btrfs that isn't mentioned. Is there a way to make that more obivous? Cause it tells me that it is an option, even with btrfs enabled.
