### ISSUE TITLE
Clean the code

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#28]
- Convert spaces to tabs where possible

**Comment by oberon-manjaro** [comment]
I'm not a fan of that. Is not everybody using spaces - or have the editor convert tabs to spaces while you edit?
manjaro-tools and calamares both use spaces - it would be quite confusing and I'd have to constantly change the settings in gedit ... :eyes:

**Comment by Huluti** [comment]
I'm agree with @oberon2007. Spaces are universal.

**Comment by Chrysostomus** [comment]
I think tabs are designed for this purpose and spaces are more cumbersome, but if they are the common manjaro practice, we should adhere to that
