### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#31]
For now I think we are fine with the PKGBUILD. Sooner or later - or in the distant future, it would maybe be good practice to have a proper makefile...? And it might even save us some confusion if we start it rather sooner than later once the thing might have grown a little more complex?
@Kirek , @Huluti , what are your plans for the weekend? :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment]
What are the benefits of having a make file on a bash script? In general I would imagine portability, but we depend on so many manjaro specific tools that this would not run even on arch. 

I'm not against it though, especially if it is good practice.

**Comment by oberon-manjaro** [comment]
You are right. I just thought that the PKGBUILD is started to look a little messy :wink: 
But I guess it's fine.
