### ISSUE TITLE
Mark submenus somehow 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#32]
Pretending > or ... Has been suggested

**Comment by oberon-manjaro** [comment]
Looking at the options, I think leading '>' makes the most sense:

![](http://imgur.com/4v9U0b1.png)

Anything trailing will look less organized, or would be a lot of extra effort to adjust the amount of needed spaces ...

**Comment by Chrysostomus** [comment]
Yes, it is not feasible to get arrows in line if they come after the text (especially with translations). And having so many ... Looks wrong. 

I would exclude the main menu from this, because everything is a submenu

**Comment by Chrysostomus** [comment]
But having the arrow at the beginning looks wrong too... It makes it seem like a subcategory of the previous item.

**Comment by oberon-manjaro** [comment]
Yes. Remember we had the same dilemma with morc_menu? :wink: 
I'm still not really familiar with dialog, but does it maybe have a way of using a third column just for the 'sub'-sign?

**Comment by Chrysostomus** [comment]
Maybe. At least some windows already take 3 arguments per item, middle one being '-'  as separator. If we could align text with this, we should use arrow at the end of the line I think.

**Comment by oberon-manjaro** [comment]
exactly. that should be possible.

**Comment by Chrysostomus** [comment]
I'll try to do something about it tonight if I can.

**Comment by oberon-manjaro** [comment]
I think I found it already, hang on!

**Comment by oberon-manjaro** [comment]
yep! works:
```
dialog --default-item ${HIGHLIGHT} --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title " $_MMTitle " --column-separator "|" \
     --menu "$_MMBody" 0 0 9 \
      "1" "$_PrepMenuTitle|>"\
      "2" "$_InstBsMenuTitle|>"\
      "3" "$_InstGrMenuTitle|>"\
      "4" "$_ConfBseMenuTitle|>"\
      "5" "$_InstNMMenuTitle|>"\
      "6" "$_InstMultMenuTitle|>"\
      "7" "$_SecMenuTitle|>"\
      "8" "$_SeeConfOptTitle|>"\
      "9" "$_Done" 2>${ANSWER}
```
I know it's not necessarily needed for the top level menu, but that's the one I can just easily test here locally on my running system :wink: 

![](http://imgur.com/Cr9MrVc.png)

**Comment by Chrysostomus** [comment]
It's fine to have them if they are on the right. 

Thanks for this, I think this is the right way to implement this!

**Comment by oberon-manjaro** [comment]
<s>They can also be closer to the text. I just thought we need spaces around the separator, but they are not needed.</s> Edited the original post without the spaces.

**Comment by oberon-manjaro** [comment]
One more idea: plus sign?
```
+ entry with submenus
+ entry with submenus
  entry without submenus
   ...
```

**Comment by oberon-manjaro** [comment]
![](http://imgur.com/9upMzFo.png)

**Comment by oberon-manjaro** [comment]
one more idea, either on the left or right, or even on both sides:

![](http://imgur.com/aFVIt5u.png)

**Comment by oberon-manjaro** [comment]
My favourite is '>' , and I would suggest we use them even on top level, so it is just logical. Also, 'done' on the top page is also an entry without submenu and it just introduces the logics of the whole menu when you start there. So you can immediately understand that there are going to be two different kinds of menu entries.

**Comment by Chrysostomus** [comment]
I agree. Let's do that.

**Comment by oberon-manjaro** [comment]
:+1: I can do it right now if you like.

**Comment by Chrysostomus** [comment]
👍

**Comment by Chrysostomus** [comment]
It think issue is now solved
