### ISSUE TITLE
not booting

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#33]
What I see of an install that I just attempted is just this:
```
Booting...
_
```
It doesn't move from there... no GRUB-screen.
**fstab** has been created, **grub** has been installed, **mkinitcpio** has been run.
What can be wrong? Where to look?

**Comment by Chrysostomus** [comment]
Initsystem or graphics drivers maybe?

**Comment by oberon-manjaro** [comment]
how check initsystem?

**Comment by Chrysostomus** [comment]
With systemd journalctl in chroot

**Comment by Chrysostomus** [comment]
Dmesg might also have something

**Comment by oberon-manjaro** [comment]
there's something strange in the errlog:

![](http://imgur.com/piLMq1m.png)

**Comment by oberon-manjaro** [comment]
vbox-video is installed

**Comment by oberon-manjaro** [comment]
https://github.com/Chrysostomus/aif-dev/blob/master/manjaro-architect#L1823

**Comment by Chrysostomus** [comment]
Any news on this?

**Comment by oberon-manjaro** [comment]
haven't found out yet what I did to run into this ... Let's just close it for now since noone else had a similar problem!

**Comment by Chrysostomus** [comment]
I think this could have been caused by the same bug that caused mhwd not getting installed.

**Comment by oberon-manjaro** [comment]
Possible. I'll try another install tonight.

**Comment by oberon-manjaro** [comment]
I got it again. It happens when I install to a single partition in vbox BIOS mode. When using a separate /boot partition there is no problem. Is this not supposed to work or do I need to set a bootflag?
Sorry if that's maybe an ignorant question :wink:

**Comment by Chrysostomus** [comment]
Did you partition manually or used automatic partitioning?

**Comment by Chrysostomus** [comment]
Maybe we could ask sueridgepipe to help diagnose the matter? I'm not very well versed with the ways of virtualbox.

**Comment by Chrysostomus** [comment]
This seems like some kind of error in installing grub.

**Comment by oberon-manjaro** [comment]
"automatic" configures with a separate /boot partition and then it is correctly mounted as boot of course. But afaik BIOS shouldn't need a separate boot partition. Maybe in that case a boot flag needs to be set. Would then probably be my job while partitioning manually ... vbox should not really make any difference there as it's supposed to simulate a real BIOS (or UEFI, depending on the setting) system.

**Comment by Chrysostomus** [comment]
Maybe. Can you verify that grub is installed on your device:

        dd bs=512 count=1 if=/dev/sda 2>/dev/null| strings

Where sda is the drive of your installation

**Comment by Chrysostomus** [comment]
Btw, is this gpt or mbr installation? According to the arch wiki

> In the case of a GPT partitioned disk it will embed it in the BIOS Boot Partition, denoted by bios_grub flag in parted and EF02 type code in gdisk

In mbr you can install it to mbr, but with gpt grub needs to go on a partition it seems. 

If you don't want separate /boot partition, maybe you can set bios_grub flag in your / partition? Just throwing ideas here.

**Comment by oberon-manjaro** [comment]
hm. seems I did something wrong with the partition table. it's not recognized at all with gdisk!

**Comment by oberon-manjaro** [comment]
but then why can I chroot into it. makes no sense. I'm doing it wrong I guess.

**Comment by Chrysostomus** [comment]
Might be. I have very little experience with legacy install. It would be good to know what is the problem though

**Comment by oberon-manjaro** [comment]
in fstab it's listed as and ext4 partition.
``strings`` returns nothing.

**Comment by oberon-manjaro** [comment]
but grub shows as is installed with ``pacman -Q``

**Comment by oberon-manjaro** [comment]
parted says "Partition table: loop" what?

**Comment by oberon-manjaro** [comment]
It looks like I certainly did something wrong when (not) creating a partition table. will try again tonight - have to go now :wink:

**Comment by oberon-manjaro** [comment]
Well in any case it's not an issue of the installer. I just ran another install flawlessly after partitioning automatically. I think we can close this :)
