### ISSUE TITLE
Is a menu-entry for mkinitcpio needed?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#35]
Would it not be better to run it at a certain point automatically? Maybe at the end of installation, immediately before we do our [final check of vital functions](https://github.com/Chrysostomus/aif-dev/issues/22)?

**Comment by Chrysostomus** [comment]
Not necessarily, but it has two purposes:

- tell the user there is such as mkinitcpio. The installer is also a learning experience 
- if the user wants to edit mkinitcpio.conf, he can then execute it to enable changes.

**Comment by Chrysostomus** [comment]
We could instead execute it after editing mkinitcpio.conf or at the end if it has not been run.

**Comment by oberon-manjaro** [comment]
Still it will be a superfluous step since there is no use in running it at any point before the last edit, so, at the very end, or is there?
In general I think it's good to have many options available, but also the installation process should  not be longer or more confusing than necessary.

**Comment by oberon-manjaro** [comment]
We now offer the user to run **mkinitcpio** after editing the config.
Apart from that the kernel hooks will execute mkinitcpio upon installation.
I think a separate menu entry it not necessary, but of course it doesn't hurt and if you like, just keep it.
In any case this here can be closed :)
