### ISSUE TITLE
allow installation of desktop-settings only if user has been installed

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#36]
"Vertrauen ist gut, Kontrolle ist besser." is a German saying :wink: 
I think upon DE-installation we need to check if a user has been created. Else the whole desktop-settings packages will be useless and this is not something the user can be expected to know! Even I made that mistake :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment]
Add a line that copies /etc/skel to all user accounts after desktop settings is installed?

**Comment by oberon-manjaro** [comment]
sure! perfect. Do it for **/root** aswell for the theming of apps run with sudo/gksu! Also some apps like nemo for example are unhappy when they don't find any of their config in root's home. manjaro-tools and calamares do it, too.

**Comment by Chrysostomus** [comment]
Solved with d91159f
