### ISSUE TITLE
Openrc services don't get enabled 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#37]
The loop to enable openrc services (lines 2204-2206) fails with "Bluetooth is not a valid runlevel" or something like that. Command inside the loop is 

     rc-update add $service default

Services are stored in /tmp/.services and the list seems fine. 

Any idea how to solve this?

**Comment by oberon-manjaro** [comment]
line 2206: ``arch_chroot "rc-update add $service"``
At the end is ``default`` missing? :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment]
Aah, maybe I did not update it yet...

**Comment by Chrysostomus** [comment]
Probably fixed with e8006df7 then

**Comment by Chrysostomus** [comment]
Nope, I get that specific error with default as runlevel. Curiously, networkmanager works just fine even though its service was not enabled.

**Comment by Chrysostomus** [comment]
At least services are not properly filtered. Bluetooth should been removed from the list, because there is no such service installed. I can fix that, but what bugs me is that the error message should still be different.

**Comment by Chrysostomus** [comment]
It was superflous quotes. FIxes with 25295f0
