### ISSUE TITLE
[dialog] some faulty arrow navigations

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#38]
In some of the dialog windows the "outer" entries ( OK | Cancel ) are not working with arrow right/left, as it should be but with up/down instead. For example the ones in ``set_root_password()``

**Comment by oberon-manjaro** [comment]
There must be something wrong with the syntax of this one and similar boxes:
```
DIALOG " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassNUsrBody $USER\n\n" 0 0 \
          2> ${ANSWER} || config_base_menu
        PASSWD=$(cat ${ANSWER})
```

**Comment by oberon-manjaro** [comment]
I get the same behaviour with the example script from this [tutorial](https://bash.cyberciti.biz/guide/A_password_box) Weird! Is this a bug in **dialog**?

**Comment by Chrysostomus** [comment]
Or maybe an undocumented feature?

**Comment by Chrysostomus** [comment]
"windows has no bugs, only undocumented features"

**Comment by oberon-manjaro** [comment]
You are right, and you are right, and you are also right in that it is apparently just strange behaviour:
It took me two days to understand how the navigation works in a password entry window :laughing: 
So: In order to use the two buttons on the bottom you have to fist move the cursor down! So far so good, but what is really freaky is that when you press UP from the text field you also circle down to the bottom of the window... ... :stuck_out_tongue:

**Comment by Chrysostomus** [comment]
Yes, it is confusing. I always try wrong options first when go to the check disk layout window

**Comment by oberon-manjaro** [comment]
In any case this seems by design. It's feature! :+1:
