### ISSUE TITLE
fstab option needed?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#39]
Do we need the alternatives or can we just stick to Manjaro standard UUID? It's a rather confusing step for non-expert users and we could even do it automatically during a final "check and finish installation" step.
Or is there a need to have this option for certain use-cases?

**Comment by Chrysostomus** [comment]
Well it needs to be before "check fstab" phase.

**Comment by Chrysostomus** [comment]
Partuuid for uefi/gpt, the other kind for mbr/legacy? I still like it that user sees the command used.

**Comment by oberon-manjaro** [comment]
We can maybe just limit the selection. Atm it's a bit overwhelming ... ?

**Comment by Chrysostomus** [comment]
Maybe. But it also tells what you should choose, no? At least for uefi.
