### ISSUE TITLE
need to check how we filter packages again

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#42]
**m-a 0.7.4.r30.g8130f55** fails installling i3 stable profile with:

![](http://imgur.com/bZ7ZqnS.png)

**Comment by Chrysostomus** [comment]
Okay, I'll check it. 

The error comes from >manjaro and  >sonar flags not being handled. Shall we support sonar at some point?

**Comment by Chrysostomus** [comment]
I had not prepared for them, because at the time no profile used those flags.

**Comment by oberon-manjaro** [comment]
I thought so. Since we have to deal with the flags anyway, sure, lets support sonar also! I still need some more time to digest all the code. Especially the packages section I haven't really looked at in detail.
If sonar is extra work, let's focus on the essential stuff first!

**Comment by Chrysostomus** [comment]
sed -i '/>sonar/d' /tmp/.edition
          sed -i 's/>manjaro //g' /tmp/.edition

**Comment by oberon-manjaro** [comment]
:+1:

**Comment by Chrysostomus** [comment]
If we want to support sonar, we can list them with 

       $(echo $PROFILES/*/*) 
Instead of 

       $(echo $PROFILES/{manjaro,community}/*

And then determine from profile.conf if the profile has >sonar flags. Then offer choice like we do with minimal/extra.

**Comment by oberon-manjaro** [comment]
do you understand why this flag still doesn't get removed?
```
manjaro-firmware
>manjaro manjaro-release
manjaro-system
```

**Comment by oberon-manjaro** [comment]
should it rather be ``sed -i 's/>manjaro//g' /tmp/.edition`` ? :wink:

**Comment by oberon-manjaro** [comment]
and then remove the spaces again? But I don't understand why just that one is still there and for the others it worked

**Comment by Chrysostomus** [comment]
No idea. What happens if you run the sed again?

**Comment by oberon-manjaro** [comment]
well it will work. but why is it there in the first place? where does the initial list get created before removing the flags?
this?
```
if [[ $(cat ${PACKAGES}) != "" ]]; then
        clear
        sed -i 's/+\|\"//g' ${PACKAGES}
        basestrap ${MOUNTPOINT} $(cat ${PACKAGES})
```

**Comment by oberon-manjaro** [comment]
well no, again doesn't work because there's no whitespace! ;)

**Comment by oberon-manjaro** [comment]
so that's the answer and the question: Why is there no whitespace!?

**Comment by oberon-manjaro** [comment]
has it something to do with the next pkg name starting with "manjaro" again?

**Comment by Chrysostomus** [comment]
No, sed operates per line. 

Does it work with sed -i 's/>manjaro//g' /tmp/.edition?

**Comment by Chrysostomus** [comment]
The file is generated like this 

      cat $PROFILES/shared/Packages-Root "$target_desktop" > /tmp/.edition

**Comment by Chrysostomus** [comment]
What is this whitespace that is missing?  I see there is a whitespace between the flag and manjaro-release in your quote.

**Comment by Chrysostomus** [comment]
If sed does not work, we can also use awk, ed or plain bash. But this should be solvable, it is just something off in pattern matching.

**Comment by oberon-manjaro** [comment]
I can look at it a little later :-) my quote was from the sourced Packages-Root file. But the resulting list in **/temp* had '>manjaro'like a package, with no white space. So running the same sed again will not help, that's what I meant ;-)

**Comment by Chrysostomus** [comment]
Aah, okay

**Comment by Chrysostomus** [comment]
I found the issue. Problem was that you had put the flag removal after this piece:

```
# remove everything except the first word of every lines
        sed -i 's/\s.*$//' /tmp/.edition

```
So before that sed command was ran, the line would have already changed from 

      >manjaro manjaro-release

to 

     >manjaro


Fixed it now, uploading the fix.

**Comment by oberon-manjaro** [comment]
:+
