### ISSUE TITLE
restructure

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#43]
I'm done with my suggestion of a re-organization of the repo on branch "makefile".
In the beginning it might look a bit irritating but in fact I think the structure is a lot clearer now. Please have a look if that's ok for you, too and if so I'd love to do the switch asap so that we don't need to committing changes to both of them - merging of differences doesn't really work anymore as they have diverged too much.

**Comment by Chrysostomus** [comment]
The structure makes sense and is what we discussed. It should hopefully make it easier for others to participate in the project too. 

I think we can make the switch. Is the new branch at feature parity?

**Comment by oberon-manjaro** [comment]
It is. Just wait a moment! I have some tiny additions still...

**Comment by oberon-manjaro** [comment]
I'm currently renaming /usr/share/aif -> manjaro-architect.
Can you please have a look at [this path](https://github.com/Chrysostomus/aif-dev/blob/makefile/lib/util-desktop.sh#L291)? Is this really correct?

**Comment by oberon-manjaro** [comment]
Re. repos I wanted to suggest this procedure:
make a new branch from the "makefile" branch and name it "manjaro-architect" and
a new branch from "master", called "aif".
After that you can make "manjaro-architect" the default branch and delete both branches "makefile" and "master". If you feel insecure about the git procedure but agree, I can do that.

**Comment by Chrysostomus** [comment]
It was, but it can be changed. It used to be in /tmp/profiles before that. I have no strong feelings about where it should be, just choose a location that makes sense to you. Maybe something like /usr/lib/manjaro-architect/profiles?

**Comment by Chrysostomus** [comment]
Maybe you can do it? I'm currently on cellphone.

**Comment by oberon-manjaro** [comment]
ah. no it's fine. i just thought it would be sourcing existent content. But so in fact 'profiles' it is only going to be created afterwards. So all is well :+1:

**Comment by oberon-manjaro** [comment]
don't do it from the cellphone, no! :scream_cat: :laughing:

**Comment by oberon-manjaro** [comment]
:+1:  done sofar. Now you just need to set the default branch to 'manjaro-architect' please before we can delete the old master branch.

**Comment by Chrysostomus** [comment]
Okay, that sounds like only repo owner can do it?

**Comment by oberon-manjaro** [comment]
yes. I don't have the settings button. but you can easily do that in the webinterface - even on the phone. you just might have to scroll to the bottom and switch to github desktop version.

**Comment by Chrysostomus** [comment]
Done

**Comment by Chrysostomus** [comment]
Would this also be a good phase to rename repo to manjaro-architect? The PKGBUILDs would need to be updated to reflect the change

**Comment by oberon-manjaro** [comment]
Excellent idea, yes! In that case please switch the default to 'aif' branch for a moment, so we can create a new 'master' branch, and then the default can go there.

**Comment by oberon-manjaro** [comment]
btw, is the 'profiles' branch still needed?

**Comment by Chrysostomus** [comment]
No

**Comment by Chrysostomus** [comment]
Done. Default branch is aif and the repo name was switched

**Comment by oberon-manjaro** [comment]
awesome. the new master is up. you can put the default there now :champagne:

**Comment by oberon-manjaro** [comment]
Fun! :smile: Thank you!
now back to the dirty work ... @[%&§$(( :eyes:

**Comment by oberon-manjaro** [comment]
And nice: github even remembers the old name and the link still works and puts you here.

**Comment by oberon-manjaro** [comment]
just don't forget to set the default back to master!

**Comment by oberon-manjaro** [comment]
Don't install the new version just, yet. Looks like I have to fix it still ...
