### ISSUE TITLE
is mhwd installed in time?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#44]
Somehow I just managed to end up in a situation where I wanted to install the video-driver, but **mhwd** was not installed to the target, yet. Should it not have been installed beforehand during base pkg install?

**Comment by Chrysostomus** [comment]
It should have and usually is. It seems you got an error at base installation

**Comment by oberon-manjaro** [comment]
hm. I still get this. after going step by step through the menu entries, when I arrive at "Install Display Driver" and select video-vbox in my case, it just flickers quickly and doesn't seem to do anything. Strangely no error message appears, but when I now look in **/tmp/.errlog** there is ``mhwd: no such file or directory``

**Comment by oberon-manjaro** [comment]
even if the cause right now is somewhere else, I think it would be good to check at this point if mhwd is installed and if not, install it here. I'll add that, ok?

**Comment by oberon-manjaro** [comment]
maybe I'll write a global ``check_pkg()`` to check for a certain pkg and install if need?

**Comment by oberon-manjaro** [comment]
something is broken with the install graphics driver function. I keep getting mhwd not known. Looks like it is trying to run mhwd on the host instead of the chroot ?

**Comment by Chrysostomus** [comment]
Weird. I'll take a look at it tonight

**Comment by Chrysostomus** [comment]
Have you checked that /mnt/usr/bin/mhwd exists?

**Comment by Chrysostomus** [comment]
Testing now. Mhwd does not get installed at least in systemd install_base.

**Comment by Chrysostomus** [comment]
It is present in base-systemd-manjaro package list though.

**Comment by Chrysostomus** [comment]
line 231 and 228 file paths are wrong

**Comment by Chrysostomus** [comment]
Fixed

**Comment by oberon-manjaro** [comment]
aaah, oops. :+1:

**Comment by Chrysostomus** [comment]
/tmp/.base had only kernel and modules, so I suspected that kernel menu would have overwritten the file. But it was set to >>, so file must have already been empty. And what could cause cat to write a empty file...

**Comment by Chrysostomus** [comment]
Kernel just pulled so many dependencies, that it seemed like the base group was being installed without a hitch.
