### ISSUE TITLE
enable cut&paste ?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#45]
@Chrysostomus is there a way we can make c&p work in the console? Or does **nano** have any builtin I am missing other than "un-cut" which seems to work only for content you have actually cut inside nano...
I think I should know that but have apparently forgotten if so :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment]
Options include tmux, screen and dvtm. Of these I recommend tmux. What do you want to use it for? 

There is also 

        sudo screendump N > screenoutput.txt
Where N is the number of the tty console you want and screenoutput.txt is the text file to which to create and save.

**Comment by Chrysostomus** [comment]
You can also try ctrl+k and ctrl+you keybindings in bash.

**Comment by Chrysostomus** [comment]
Do I understand correctly that you want to copy something from nano and paste it somewhere else?

**Comment by oberon-manjaro** [comment]
**tmux** is already installed. How does it work?
Useful for example to paste code from outside vbox ... ;)

**Comment by oberon-manjaro** [comment]
bidirectional would be great - if possible...

**Comment by Chrysostomus** [comment]
Aah. So there is also vbox involved... Might be tricky...

**Comment by Chrysostomus** [comment]
You use tmux like this:
1) run tmux 
2) continue to use console as normal 

For copy and paste... Well it depends on what your settings are. You enter the copy mode, then start and stop selection with space. Move cursor with arrow keys. Here is small introduction...  https://gist.github.com/MohamedAlaa/2961058

**Comment by Chrysostomus** [comment]
I don't think this communicates outside virtualbox though.

**Comment by Chrysostomus** [comment]
https://forums.virtualbox.org/viewtopic.php?f=8&t=37956

**Comment by oberon-manjaro** [comment]
thanks! I'll check out tmux some more. It's not utterly important in any case.
