### ISSUE TITLE
default base-pkgs

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#49]
At the moment we have no kernel pre-selected.
Should we maybe pre-select **linux49**, being the recommended kernel?
And what about these three:
```
"KERNEL-headers" "-" on \
"KERNEL-acpi_call" "-" on \
"KERNEL-ndiswrapper" "-" on \
```
Is it a good idea to have them ticked?

**Comment by Chrysostomus** [comment]
I don't know. I chose ndiswrapper because my system has it installed by mhwd, acpi_call because it sounded nice and headers in case someone uses dkms stuff.

Problem with preselecting kernels is that we would need to manually update it as the recommended kernel changes.

**Comment by oberon-manjaro** [comment]
:laughing: awsome!
You're probably right about the kernel. Headers maybe we don't need to preselect since people you want to use **dkms** likely know what they are doing and that they need the headers. acpi_call and ndiswrapper don't really matter, the headers however are bigger package, so maybe I wouldn't suggest them?

**Comment by Chrysostomus** [comment]
Works for me
