### ISSUE TITLE
check_pkg is broken

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#57]
1) You cannot use [[ ]] inside manjaro-chroot, because it executes stuff with sh instead of bash
2) Multiple commands like this don't work inside manjaro-chroot in noninteractive mode. In my experience all && and || stuff fails. 

We should just check if appropriate stuff is present in /mnt/usr/bin. Simpler and less error prone.

**Comment by papajoker** [comment]
but all package dont have a bin et not all package have the same name/bin ?

**Comment by Chrysostomus** [comment]
Yeah, we need to figure something out. I now put in temporary function that just warns about missing package. If things like mhwd is missing, it means that the install_base has done something wrong, and just slapping in mhwd won't fix it.

**Comment by papajoker** [comment]
you cant write (not tested, not sure of arch_chroot return) ?

```
if ! arch_chroot "pacman -Q $1" 2>/dev/null ; then
      arch_chroot "pacman -Sy --noconfirm $1" 2>$ERR 
      check_for_error "install missing pkg $1 to target." "$?"
fi
```

**Comment by Chrysostomus** [comment]
Yeah, something like that should work better. I'll test it.

**Comment by Chrysostomus** [comment]
Okay, this seems to work:

```
check_pkg() {
if ! arch_chroot "pacman -Q $1" ; then
      basestrap "$1" 2>$ERR 
      check_for_error "install missing pkg $1 to target." "$?"
fi
}

The output redirection does not seem to affect anything inside the chroot, but that is okay, the output is nonintrusive.
```
