### ISSUE TITLE
Check_for_error should not return user to main menu

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#58]
I think it would be better if check_for_error would return user to the previous submenu instead. Do you think this would be feasible?

**Comment by papajoker** [comment]
yes/no, we can  : 
add a param 3 function

chech_for_error "title" errorcode menufunction

if error
      if not ($3) call main_menu_online else call $3
fi

i prepare a PR #59

**Comment by Chrysostomus** [comment]
We need some kind of flag for check_for_error that allows installation to proceed. For example, checking for error with current function prevents the installation unnecesarily if vconsole.conf or pacman.conf is missing. Alternatively, we can just not check for error in those places. They return 1 half the time and it is completely harmless.

**Comment by Chrysostomus** [comment]
Maybe we could just not move user anywhere with this function? The problem currently is that check_for_error blocks installation when
- any errors occur 
- when used in conjunction with [[ ]] that return 0.

It should at the very least have a switch that allows process to continue on error. That might be the best solution. 

@papajoker @oberon2007 what do you think?

**Comment by papajoker** [comment]
good morning ;)

now chech_for_error is strict if you read end of  #59 
We must test the return command and not the return of the dialog
for all `chech_for_error` write after dialog **--yesno** with the good stucture

```
if dialog --yessno "..." 0 0 ; then
     COMMAND 2>$ERR
     chech_for_err "run COMMAND" $?
#else # if you want a log
#     chech_for_error "skip COMMAND ..." 0
fi
```

and as dialog, if we have a test

BAD stucture

    [ test ] && COMMAND 2>$ERR
    chech_for_error "run COMMAND" $?  # return test errcode if test = false

very BAD stucture

    [ test ] && COMMAND 2>$ERR && chech_for_error "run COMMAND" $?
    # if error in command, never call  test errcode

good

```
if [ test ] then
     COMMAND 2>$ERR
     chech_for_error "run COMMAND" $?
fi
```

good
```
[ test ] && { COMMAND 2>$ERR;  chech_for_error "run COMMAND" $?; }
```

**Comment by oberon-manjaro** [comment]
Can you for those instances where you want to continue not just pass ''continue'' as the third argument?

**Comment by oberon-manjaro** [comment]
What does "DAB" mean? ;)

**Comment by papajoker** [comment]
YES (or not...) !!!!
we have already a third arg, if we pass "SKIP", dont call the menu_function and no dialog

```
# param 3 : return menu function , optional, default: main_menu_online, SKIP: no dialog and return
check_for_error() {
  ...
       if [[  "${_function_menu}" != "SKIP" ]]; then
           DIALOG " $_ErrTitle " --msgbox "\n${_msg}\n" 0 0
           ($_function_menu)
       fi 
 ...
}
```
I let you make the change if you want this
and we can write : 

    [ test ] && COMMAND 2>$ERR
     chech_for_error "run COMMAND" $? "SKIP"

### BUT the log is **false** !! if test=false, no call COMMAND but we have the log and $? is not the return of the command
$? is the return code of the test (or dialog) **1** !!!


    [[ 1 = 2 ]] && echo "command" ; echo $?
    # $? return always 1 !
-----
DAB is bad -)

**Comment by Chrysostomus** [comment]
I think this is complete
