### ISSUE TITLE
if then but not fi

### ISSUE THREAD

**Issue by papajoker** [Chrysostomus/aif-dev#60]
in this line https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-base.sh#L450
i cant view the fi  ?

                # If an installation method has been chosen, run it
                if [[ $(cat ${PACKAGES}) != "" ]]; then
                    arch_chroot "$(cat ${PACKAGES})" 2>$ERR
                    check_for_error "syslinux-install" "$?"

                # Amend configuration file. First remove all existing entries, then input new ones.

apparently just indent ?

EDIT:
OK find, the bad offset begin L443 at https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-base.sh#L443

not a problem with if ... check_for_error sorry

**Comment by oberon-manjaro** [comment]
brr, confusing bit :stuck_out_tongue_winking_eye: 
Like that now, right?
