### ISSUE TITLE
check for availability of openrc

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#64]
I think we should check if a given profile supports openrc or not. We can still adjust most of the missing ones, but certain like for example Deepin do not play well, others are not ready.
How about we check if at least one ``>openrc`` flag is present in the profile and if not we disable the choice?

**Comment by oberon-manjaro** [comment]
Or in fact we'd need to check which base install is present and then inhibit the choice of certain profiles.

**Comment by oberon-manjaro** [comment]
maybe some kind of an evaluate_profiles function at the beginning of **install_manjaro_de_wm()**

**Comment by Chrysostomus** [comment]
Should we check for ">openrc" flags to see if profile is viable?

**Comment by oberon-manjaro** [comment]
in **install_manjaro_de_wm()**
```
cat $PROFILES/shared/Packages-Root "$target_desktop" > /tmp/.edition
        if [[ -e /tmp/.openrc ]]; then
            [[ ! $(grep ">openrc" /tmp/.edition) ]] && DIALOG ... ...
            # Remove any packages tagged with >systemd and remove >openrc tags
```
Where it says "DIALOG ... ..." we could offer a choice to either return to profile selection or back to base install to change the init sys

**Comment by oberon-manjaro** [comment]
The only situation where it would be wrong would be an openrc-only profile that would carry no >openrc flags - but we don't have such currently and it is pretty unlikely, too ;)

**Comment by Chrysostomus** [comment]
I think it's best if we just filter the profile selection based on the base.

**Comment by oberon-manjaro** [comment]
```
if [[ ! $(grep ">openrc" /tmp/.edition) ]]; then
    DIALOG "no openrc version" --menu "This profile is currently not available for openrc\nPlease adjust your selection:" 0 0 2 \
      "1" "Select different profile" \
      "2" "Install systemd base" 2>${ANSWER}
    case $(cat ${ANSWER}) in
        "1") install_desktop_menu
            ;;
        "2") install_base
            ;;
    esac
fi
```

**Comment by oberon-manjaro** [comment]
Is filtering the profiles first easier to accomplish?
The advantage of the just proposed would be that the user sees that a profile is available if they use systemd base.

**Comment by oberon-manjaro** [comment]
Otherwise those profiles just disappear.

**Comment by Chrysostomus** [comment]
Good point. Could we also tag openrc capable profiles with '*' or something? That way users would not need to blindly test different options to see which ones are working. 

Also, I think the menu should read "install systemd base" instead of "install openrc bsse". 

Another distantly related point: would it be a good idea to place the openrc check file in /mnt/.openrc instead of /tmp/.openrc?

**Comment by oberon-manjaro** [comment]
1) do we have a way to check the profiles before the package list gets copied? If so we could just include that information in the init sys dialog
2) of course, my bad ;) - edited the post.
3) don't know. why you mean?

**Comment by oberon-manjaro** [comment]
1. we don't. The only way is at profile selection of course ;)

**Comment by oberon-manjaro** [comment]
so we'd need to evaluate all profiles first and then find a way to deliver the information at profile selection.

**Comment by oberon-manjaro** [comment]
Also, maybe at that point an option to go back to re-install base with systemd would make sense ... ?

**Comment by oberon-manjaro** [comment]
btw. since the architect profile is now also included in **iso-profiles** repo we will have to exclude it from installable profiles! :laughing:

**Comment by oberon-manjaro** [comment]
```
echo $PROFILES/{manjaro,community}/* | xargs -n1 | cut -f2 -d'/' | grep -vE "netinstall|architect" | awk '$0=$0" - off"'
```
btw: why is there ``cut -f7`` at the moment ??

**Comment by Chrysostomus** [comment]
Cuts away the directory path to only print the profile names instead of the full paths.

**Comment by oberon-manjaro** [comment]
Sure thing. But I mean, why is it 7 and not 2 ??

**Comment by oberon-manjaro** [comment]
when I run the command locally in my iso-profiles dir I need -f2. when I use -f7 it returns an empty list:
```
[bernhard@oberon iso-profiles]$ echo {manjaro,community}/* | xargs -n1 | cut -f7 -d/ | grep -vE "netinstall|architect" | awk '$0=$0" - off"'
 - off
 - off
 - off
 - off
 - off
 - off
 - off
 - off
 - off
 - off
 - off
 - off
```

**Comment by oberon-manjaro** [comment]
while using -f2:
```
[bernhard@oberon iso-profiles]$ echo {manjaro,community}/* | xargs -n1 | cut -f2 -d/ | grep -vE "netinstall|architect" | awk '$0=$0" - off"'
gnome - off
kde - off
lxqt - off
xfce - off
bspwm - off
budgie - off
cinnamon - off
deepin - off
i3 - off
mate - off
```

**Comment by Chrysostomus** [comment]
The git profiles are with -f2. The package profiles are deeper in directory path and need -f7. Are you sure you aren't mixing the two?

**Comment by oberon-manjaro** [comment]
I am ;) sorry.

**Comment by oberon-manjaro** [comment]
no actually, I only assumed $PROFILE to be the last layer. That was the mistake...

**Comment by Chrysostomus** [comment]
3.If you install openrc base, reboot and remount your system, installing any profile fails because system does not recognize that the base is openrc and filters packages as if it was systemd

**Comment by oberon-manjaro** [comment]
excluded architect profile: https://github.com/Chrysostomus/manjaro-architect/commit/3814fb75f986941d16074e15c1d4681cdb5917b3

**Comment by oberon-manjaro** [comment]
good point about using **/mnt/.openrc** ! :+1: 
I guess we should do the same for [**.base_installed**](https://github.com/Chrysostomus/manjaro-architect/blob/1aac7b3bae2ee062c926168b7e90e5cf98a35e0a/lib/util-base.sh#L325)

**Comment by oberon-manjaro** [comment]
```
# return list of profiles not containing >openrc flag in Packages-Desktop
evaluate_profiles() {
  echo "" > /tmp/.systemd_only
  for p in $(find $PROFILES/{manjaro,community} -mindepth 1 -maxdepth 1 -type d ! -name 'netinstall' ! -name 'architect'); do
    [[ ! $(grep ">openrc" $p/Packages-Desktop) ]] && echo $p | cut -f7 -d'/' >> /tmp/.systemd_only
  done
  echo $(cat /tmp/.systemd_only)
}
```

**Comment by oberon-manjaro** [comment]
```
$ evaluate_profiles
bspwm deepin cinnamon i3
```

**Comment by oberon-manjaro** [comment]
We can then simply use a text tring like this in the profile selection dialog:
```
These profiles are currently available for systemd base only:\n\n$(evaluate_profiles)
```

**Comment by oberon-manjaro** [comment]
https://github.com/Chrysostomus/manjaro-architect/commit/976bb582dd2116623b2926f9cae86280a77221c0
https://github.com/Chrysostomus/manjaro-architect/commit/eb930c83b5ef16f29b2116f366855a01d61aa1e7

**Comment by oberon-manjaro** [comment]
I'll update **manjaro-architect-dev** / **manjaro-architect-dev-launcher** packages for testing in vbox and such ...
