### ISSUE TITLE
/mnt/.openrc should not be removed during quit dialog

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#68]
I just ran into this scenario:
After installing base I quit the installer, then remounted then later re-launched it and started installing a DE, using the already installed base.
Now **/mnt/.openrc** had been removed, leading to trouble :wink:

**Comment by Chrysostomus** [comment]
Yes, when it resided in /tmp it was good to remove it, but /mnt should have permanent setting.
