### ISSUE TITLE
avoid re-installing pkgs

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#69]
Should it not be quite simple to remove packages from the list of desktop installation that have already be installed during base install?
Save a list like [this one](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-base.sh#L312) and then compare the desktop pkgs list against it later?

**Comment by Chrysostomus** [comment]
I tried to something similar earlier, but found it pointless since pacman just skips over installed packages anyway. Of course it looks better though

**Comment by papajoker** [comment]
if you use --needed you have the same functionality ?

filter pkgs : 

    echo "a b c d e f" | tr ' ' '\n ' | grep -vE $(echo "b c d"|tr ' ' '|')

    chroot-manjaro "pacman-Qq" >installed_list
    filter_list=$( grep -Ev $(<"to_install_list"|tr ' ' '|') <(<"installed_list"|tr ' ' '\n') )
    chroot-manjaro "pacman -S $filter_list"

**Comment by oberon-manjaro** [comment]
In any case pacman doesn't skip. Pkgs are not downloaded again but they will be reinstalled... ;)

**Comment by Chrysostomus** [comment]
Basestrap seems to skip. I might be wrong though. But I don't have anything against filtering the list, it is cleanest any way.

**Comment by papajoker** [comment]
ok 
a filter as 

    function filter_pkgs() {
       grep -Ev $(chroot-manjaro "pacman-Qq" | tr '\n' '|') <(echo "$1" | tr ' ' '\n')
       #return error in pacman if return is empty
    }
    basestrap ${MOUNTPOINT} $(filter_pkgs "pacman git bash")

**Comment by oberon-manjaro** [comment]
Since apparently testing ``pacman -Q`` in the chroot is problematic, we could instead just write **/tmp/.base** to a file in the chroot - so in case we want to continue after a reboot or later for whatever reason it will contain what is actually the target's base install.
Then before desktop pkgs get installed we compare the two lists for unique entries of the new list.

**Comment by Chrysostomus** [comment]
Base installation are written in /tmp/.base. Manjaro-desktop packages are written in /tmp/.edition. We could just 

         basestrap ${MOUNTPOINT} $(grep -v -f /tmp/.base /tmp/.edition)

**Comment by papajoker** [comment]
I did not know basestrap !
in  /tmp/.base we dont have dependences , only explicits

for me, when manjaro-architect run, in other console this command is good, for only local query -b is enough :  

    pacman -Q -b /mnt/var/lib/pacman/
    # with --debug : database path for tree core set to /mnt/var/lib/pacman/sync/core.db

ps in this [ function check_pkg()](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util.sh#L376) you use arch_chroot ? function used only by check_pkg mhwd()

**Comment by oberon-manjaro** [comment]
Ah. So does ``pacman -Q`` work in the chroot @Chrysostomus ? My memory was that you had to change check_pkg() for that - maybe I'm mistaken? ;)

**Comment by Chrysostomus** [comment]
Pacman -Qqg works, but piping or output redirection does not. Something like this might work though:

      arch_chroot 'pacman -Qq' > /tmp/.installed
This redirects the output of the chroot command, which is fine.

**Comment by oberon-manjaro** [comment]
Very nice! :+1: 

cinnamon profile before: ![](http://imgur.com/ZwhliQ7.png)

now: ![](http://imgur.com/Q2lSTKt.png)
