### ISSUE TITLE
Check_for_error in exit may prevent closing installer

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#71]

**Comment by oberon-manjaro** [comment]
why? I thought when you only use one arg, the 2nd will default to 0. So no error will be detected.
did I still not get that right?? :stuck_out_tongue_winking_eye:

**Comment by oberon-manjaro** [comment]
I thought if it is just
``check_for_error "exit installer."``
it will never do more than write to log, no?

**Comment by papajoker** [comment]
is not a bug in program structure from the beginning ?
when i write in log functions path i [was](https://github.com/Chrysostomus/manjaro-architect/pull/59#issue-209528988) :  

02/22/17 18:28:15 [rank mirrors][1]  --configure_mirrorlist()<-configure_mirrorlist()<-install_base_menu()<-**main_menu_online**()<-check_base()<-**main_menu_online**()<-check_base()<-**main_menu_online**()<-prep_menu()<-**main_menu_online**()<-check_base()<-**main_menu_online**()<-prep_menu()<-prep_menu()<-lvm_create()<-lvm_menu()<-prep_menu()<-luks_menu()<-luks_open()<-luks_menu()<-prep_menu()<-mount_partitions()<-prep_menu()<-select_device()<-prep_menu()<-**main_menu_online**()<-main()]

here we can view many main_menu_online() Imbricated for exemple check_for_error call main_menu_online "in main_menu_online"
So do not we have multiple stacked exit of this function?

**Comment by Chrysostomus** [comment]
I do not understand what you mean @papajoker, but if I try to exit after using Luks menu, check for error returns me to that menu instead of letting installer close.

**Comment by papajoker** [comment]
https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-menu.sh#L49
no sens check_for_error "" $?

    if [[ $? -eq 0 ]]; then  # $? is the returncode of dialog : YES
       check_for_error "exit installer." $? "SKIP"   # $? is returncode of test [[ ... ]] !!!!!!
    fi

**Comment by Chrysostomus** [comment]
Maybe we should just remove error checking from exit?

**Comment by papajoker** [comment]
for me, the issue problem is not in this code

**Comment by Chrysostomus** [comment]
Ok, it is something else then.

**Comment by oberon-manjaro** [comment]
The chain of functions in your post @papajoker, is it not maybe normal in an infinite loop?

**Comment by oberon-manjaro** [comment]
For now lets see if it makes a difference to just leave the exit and umount process alone with checking for errors ;) https://github.com/Chrysostomus/manjaro-architect/commit/5af8ada8c1a40da966e09e682fa99ab69dfec664
Maybe it wouldn'd be a bad idea in general to just use a clean separate logging function in places where we really want need more than ``echo "message" >> $LOGFILE`` ;)

**Comment by Chrysostomus** [comment]
I think I would want tee - a $LOGFILE in some places. Mainly grub-mkconfig and service enablement parts. Instead of just exit status it would be good to have actually output of the commands..

**Comment by oberon-manjaro** [comment]
You are right, yes! It was the original plan, right - just somehow seems we got carried away by that check-error toy ... :blush:

**Comment by oberon-manjaro** [comment]
@Chrysostomus for me the strange behaviour has disappeared with the [latest changes](https://github.com/Chrysostomus/manjaro-architect/commit/5af8ada8c1a40da966e09e682fa99ab69dfec664). Can you verify if it also solves the LUKS exit issue?

**Comment by Chrysostomus** [comment]
I'll test it when the night falls.

**Comment by oberon-manjaro** [comment]
for recording of output will something like this work?
```
record() {
    echo ":: $1 ::" >> $LOGFILE
    $1 2>&1 | tee >> $LOGFILE
}
```

Then we can do for example
```
record "basestrap ${MOUNTPOINT} $(cat ${PACKAGES})"
```

Now I just don't know what this will mean for exit codes and if we can still create error messages after such a tee'ed event. Can the ``2>$ERR`` still go inside? Or will ``$ERR`` be empty because of the tee redirect to file?
Also to be honest I don't know how you can use that when the command contains quotes... - Can we escape them? like:
```
record "arch_chroot \"grub-install --target=i386-pc --recheck $DEVICE\""
```
or will that break the commands?
