### ISSUE TITLE
check if all profiles work for installation with m-a

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#72]
Maybe we can collect information here about our own tests, feedback from the forum and the profile maintainers.
In case somewone still needs to know, the architect-ISO can be downloaded from [here].(https://sourceforge.net/projects/manjaro-architect/files/architect/dev/)

**Xfce**
- [x] systemd
- [x] openrc

**KDE**
- [x] systemd
- [x] openrc

**GNOME**
- [x] systemd

**Lxqt**
- [x] systemd
- [x] openrc

**Bspwm**
- [x] systemd
- [x] openrc 

**Budgie**
- [x] systemd

**Cinnamon**
- [x] systemd

**Deepin**
- [x] systemd

**i3**
- [x] systemd
- [x] openrc

**Mate**
- [x] systemd
- [x] openrc

**Comment by oberon-manjaro** [comment]
@Ste74 would you like to test your profiles with the new installer? Do we know how well Budgie plays with openrc in principle?

**Comment by oberon-manjaro** [comment]
Feedback from the forum about KDE I think suggests that both init systems were successfull, right? @Kirek , maybe you'd like to attempt an install once?

**Comment by Ste74** [comment]
😜 :) i never used openrc , can be the occasion to test it :D 
Download the iso and test in vbox .. gnome not sure if with openrc will work because gnome and systemd are big friends and with openrc big issue ( i think ) . Let me see all profiles 😃

**Comment by oberon-manjaro** [comment]
Great! Thank you, @Ste74, thank you! :smiley: 
Meanwhile I have installed an **lxqt** openrc - :+1: that one is checked.

**Comment by Chrysostomus** [comment]
Gnome does not need to be even checked, it depends on systemd

**Comment by oberon-manjaro** [comment]
I see. So since the >openrc flags in gnome's Packages-Desktop list serve no purpose :wink: Would it be possible to remove them @Ste74 ? Because **m-a** recognized systemd-only profiles by scanning for those flags, see...?

**Comment by oberon-manjaro** [comment]
I assume bspwm systemd box can be checked ? ;)

**Comment by Chrysostomus** [comment]
Systemd one can, openrc support comes later. How do you tick those boxes that the selection remains? I already checked bspwm box earlier.

**Comment by oberon-manjaro** [comment]
ah, yes. it's ticked already, sorry! :)

**Comment by Chrysostomus** [comment]
Kde seems to be missing xdm-service. Package displaymanager-openrc is missing even though it is on the Packages-Desktop

**Comment by Chrysostomus** [comment]
There must be something wrong with package filtering again...

**Comment by Chrysostomus** [comment]
Happens with both full and minimal profile

**Comment by Chrysostomus** [comment]
Its the part where /tmp/.base packages are filtered out of the list. I think we need to revert that commit... 

Fixed now.

**Comment by oberon-manjaro** [comment]
Fixed? Did you just remove the filter again? I don't see how the grep -v could remove displaymanager-openrc. Or was it not installed in the first place? Then it's a problem during base install. But then again that should have failed and never written the **.base_installed** file...

**Comment by Chrysostomus** [comment]
For some reason grep -f $file misbehaves when piped into. I just removed the useless cat and used grep directly. The cat used to serve a purpose, but since the input drivers were fixed in profiles, cat is unnecessary

**Comment by Chrysostomus** [comment]
Mate works with openrc. No reason to think it would not work with systemd, but I'll check

**Comment by Ste74** [comment]
Budgie 10.x depends more on gnome stuck/api , tonight try it but not sure if work.. Budgie 11 will to see ( migration on qt )

**Comment by Ste74** [comment]
Ok budgie and gnome is out of openrc init system ......

> I see. So since the >openrc flags in gnome's Packages-Desktop list serve no purpose :wink: Would it be possible to remove them @Ste74 ? Because m-a recognized systemd-only profiles by scanning for those flags, see...?

Yes i think i can do :) If gnome not can be used with openrc why not ..

**Comment by Chrysostomus** [comment]
Btw, we should add gnome to the list of incompatible desktops. Currently the installer warns about bspwm, cinnamon and budgie, but not gnome.

**Comment by oberon-manjaro** [comment]
yes. we just need to decide if we can simply achieve that by removing >openrc flags from the respective profiles or if we need to deal with it differently in the installer. Actually it seems quite elegant at the moment and also I don't see why a profile should contain flag suggesting something that isn't going to happen... :wink: @Ste74 ?

**Comment by Chrysostomus** [comment]
Budgie works otherwise, but it has the same displaymanager problem as mate profile used to have.

**Comment by Chrysostomus** [comment]
Bspwm profile now has some preliminary openrc support too. Just no easy way to set autologin, and nothing to manage laptop lid actions

**Comment by oberon-manjaro** [comment]
I half-checked the box :wink:
