### ISSUE TITLE
something wrong with umount_partitions() ?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#73]
@Chrysostomus , @papajoker could you please have a look at [this function](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-disk.sh#L8)?
What is it there about ``$err`` ? I don't understand.
Sometimes when aborting the installer on the way, it doesn't seem to want to close down properly and sometimes jumps back to somewhere in the menu.
I wonder if in fact this has nothing to do with our new [exit function](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-menu.sh#L47) but is related to this ``umount_partitions()`` function here?

**Comment by Chrysostomus** [comment]
This issue is same as #71, I think.

**Comment by oberon-manjaro** [comment]
I don't see how ``$(umount $i >/dev/null 2>$ERR)`` can be the 2nd arg in ``check_for_error``
Really??
``check_for_error "$FUNCNAME $i" $(umount $i >/dev/null 2>$ERR)``

**Comment by Chrysostomus** [comment]
Looks confusing

**Comment by papajoker** [comment]
its my code !
![edit](https://lut.im/1wo2fBXknF/4JTS0TrbRZ1gIlHm.png)
i wanted write in log ONLY if error . if ok no reason to write, for me it was information without interest

**Comment by Chrysostomus** [comment]
Aah, makes sense.

**Comment by papajoker** [comment]
and i use $err, 
because this code is false [as this](https://github.com/Chrysostomus/manjaro-architect/issues/71#issuecomment-282941626) : 

        umount $i >/dev/null 2>$ERR
        (( $? !=0 )) && check_for_error "$FUNCNAME $i" $?   # second $? alway = 0

second $? pass to func check_for_error is the test returncode ((..)) not umount command

**Comment by oberon-manjaro** [comment]
Since it's not really needed, maybe we can just comment that bit out for now until we have nailed down the real issue? There's just a bit too much loooooping going on right now maybe... :stuck_out_tongue_winking_eye:

**Comment by oberon-manjaro** [comment]
https://github.com/Chrysostomus/manjaro-architect/commit/c214f65311ce588c5040b929c4b18cd44b778758#commitcomment-21098779

**Comment by oberon-manjaro** [comment]
working now for me.

**Comment by oberon-manjaro** [comment]
Reopening, since I seem to have the [same issue](https://github.com/Chrysostomus/manjaro-architect/pull/78#issuecomment-283251415) with the reorganized script - The cause seems to be still somewhere other than recursiveness ...
However please test with the old structure if this is solved or not, or if it has to do with the new main_menu loop.?
