### ISSUE TITLE
Something wrong with installation of git profiles 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#75]
Reported by eugen-b: https://forum.manjaro.org/t/unstable-manjaro-architect-beta-testing/16010/537

**Comment by oberon-manjaro** [comment]
strange. 
We have
```
if [[ -f $PROFILES ]]; then
        git -C $PROFILES pull 2>$ERR
        check_for_error "pull profiles repo" $? install_graphics_menu
    else
        git clone ...
```
It doesn't make sense really that the installer would attempt to clone the repo and fail.

**Comment by Chrysostomus** [comment]
It is this:

       [[ -f
-f switch checks for regular files. We need -d or -e switch. I wonder how it got like that...

**Comment by oberon-manjaro** [comment]
True. I was wondering, but then forgot again. Seems I introduced this alrady back then when we added profiles pkgs. I guess at that point I thought $PROFILES was a list ... :wink: 
Will fix.
