### ISSUE TITLE
Split installer to simple and advanced version 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#77]
There have been requests to simplify the installer. One option would be to split the installer to two variants. If we do this I suggest waiting until installer is restructured. 

For the simple installer, we could 

- drop git profile installation and unconfigured desktops 
- drop networking and multimedia menu 
- unite vconsole and Xorg keymap setting 
- automate fstab generation, mkinitcpio and some other stuff in the exit 
- merge base installation and profile installation?

**Comment by Chrysostomus** [comment]
Maintaining 2 versions would be a lot of extra work though

**Comment by Chrysostomus** [comment]
To make it work, we could merge some simplifications to main version, keep differences to the level of main menu. We could then have just have two separate main menu functions, maybe chosen at runtime with a command line switch. 

To ease this, we could move networking capabilities menu and multimedia menu under the unconfigured desktops menu. Then the difference could be just where the graphics menu takes you: submenu or straight to profile selection. It could actually be done within one function even...

**Comment by papajoker** [comment]
It should be able to adapt to a community iso, without dialogue for soft part.
For example call by:

    manjaro-architect --desktop=i3 [--arch=i386] [--init=systemd] [--minimal] [--nogrub] --extra="dev-tools,gnome-extra"

if "param" present, not show menu but directly use param

Add also for hard for Automated tests and Advanced users

    manjaro-architect --dsys="/dev/sda5" --dhome="/dev/sda6" [-f ext4] ...

**Comment by Chrysostomus** [comment]
interesting idea, though quite different than what I suggested.

**Comment by papajoker** [comment]
not the same ?

     manjaro-architect --desktop=net-edition

**Comment by papajoker** [comment]
Architecture is the same, exit the static menus, use dynamic menus
After we are free to automate things

**Comment by Chrysostomus** [comment]
Aah! You mean that we would generate menus dynamically based on the command line options? So it is a new idea to fulfill the same goal?
