### ISSUE TITLE
Issues with the new structure 

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#80]
Since @oberon2007 branch does not have issues enabled, I'll list some here:

Bugs:
- [ ] cancel does not work in Luks (and maybe lvm) submenu after the first level 
- [ ] $HOME is owned by root if user is created before installing desktop 
- [ ] check_mount is triggered by exit 
- [ ] functions should not end with return 0

Enhancements:
- [ ] add final_check
- [ ] combine vconsole and Xorg keymap setting to a keyboard menu 
- [ ] add some automation to the exit

**Comment by oberon-manjaro** [comment]
add final check? is it not working? it did with my first test-run! Or you mean something more elaborate? ;)
I have opened separate issues at my repo for the bugs listed above.
We can also create a new branch here and move the stuff back to your repo. Or we just wait a little longer and then merge it into master? I have checked for the conflicts and it would (surprisingly) still not be a big deal to resolve them.
