### ISSUE TITLE
customize dialog ?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#81]
If we want to change the default appearance of dialog it can be done with configuration in **~/.dialogrc**
```
# Run-time configuration file for dialog
#
# Automatically generated by "dialog --create-rc <file>"
#
#
# Types of values:
#
# Number     -  <number>
# String     -  "string"
# Boolean    -  <ON|OFF>
# Attribute  -  (foreground,background,highlight?)

# Set aspect-ration.
aspect = 0

# Set separator (for multiple widgets output).
separate_widget = ""

# Set tab-length (for textbox tab-conversion).
tab_len = 0

# Make tab-traversal for checklist, etc., include the list.
visit_items = OFF

# Shadow dialog boxes? This also turns on color.
use_shadow = ON

# Turn color support ON or OFF
use_colors = ON

# Screen color
screen_color = (CYAN,GREEN,ON)

# Shadow color
shadow_color = (BLACK,BLACK,ON)

# Dialog box color
dialog_color = (BLACK,WHITE,OFF)

# Dialog box title color
title_color = (BLUE,WHITE,ON)

# Dialog box border color
border_color = (WHITE,WHITE,ON)

# Active button color
button_active_color = (WHITE,BLUE,ON)

# Inactive button color
button_inactive_color = (BLACK,WHITE,OFF)

# Active button key color
button_key_active_color = (WHITE,BLUE,ON)

# Inactive button key color
button_key_inactive_color = (RED,WHITE,OFF)

# Active button label color
button_label_active_color = (YELLOW,BLUE,ON)

# Inactive button label color
button_label_inactive_color = (BLACK,WHITE,ON)

# Input box color
inputbox_color = (BLACK,WHITE,OFF)

# Input box border color
inputbox_border_color = (BLACK,WHITE,OFF)

# Search box color
searchbox_color = (BLACK,WHITE,OFF)

# Search box title color
searchbox_title_color = (BLUE,WHITE,ON)

# Search box border color
searchbox_border_color = (WHITE,WHITE,ON)

# File position indicator color
position_indicator_color = (BLUE,WHITE,ON)

# Menu box color
menubox_color = (BLACK,WHITE,OFF)

# Menu box border color
menubox_border_color = (WHITE,WHITE,ON)

# Item color
item_color = (BLACK,WHITE,OFF)

# Selected item color
item_selected_color = (WHITE,BLUE,ON)

# Tag color
tag_color = (BLUE,WHITE,ON)

# Selected tag color
tag_selected_color = (YELLOW,BLUE,ON)

# Tag key color
tag_key_color = (RED,WHITE,OFF)

# Selected tag key color
tag_key_selected_color = (RED,BLUE,ON)

# Check box color
check_color = (BLACK,WHITE,OFF)

# Selected check box color
check_selected_color = (WHITE,BLUE,ON)

# Up arrow color
uarrow_color = (GREEN,WHITE,ON)

# Down arrow color
darrow_color = (GREEN,WHITE,ON)

# Item help-text color
itemhelp_color = (WHITE,BLACK,OFF)

# Active form text color
form_active_text_color = (WHITE,BLUE,ON)

# Form text color
form_text_color = (WHITE,CYAN,ON)

# Readonly form item color
form_item_readonly_color = (CYAN,WHITE,ON)
```
low priority! :wink:

**Comment by papajoker** [comment]
tested not simple the colors choice, add in source:

     export DIALOGRC="$PWD/data/.dialog.rc"

**Comment by oberon-manjaro** [comment]
well we could simply deploy the config file to the live user's home with manjaro-tools. But it's really not high priority! ;)

**Comment by oberon-manjaro** [comment]
when manjaro-tools creates user 'manjaro' in the live session, whatever has been installed to **/etc/skel** via overlay or by a settings-package will end up in **/home/user/manjaro/...**
so that should not be a problem.

**Comment by oberon-manjaro** [comment]
I was just looking at the package **console-solarized** and how they achieve the costomized console colors. They use systemd getty services and export the colors with a script. For the architect ISO It wouldn't be a problem to do the same.
Like that we are free to not use only the few pre-defined console colors but can modify them to whatever we like. We have 16 colors available to define with hexcodes - more than we could possibly ever use! ;)
```
some_color0="123abc"
some_color1= ...

echo -en "\e]P0$some_grey"   # Black
echo -en "\e]P1$some_red"    # Red
echo -en "\e]P2$some_green"  # Green
...
echo -en "\e]Pe$..."
echo -en "\e]Pf$..."
```

**Comment by oberon-manjaro** [comment]
**dialogrc** is a bit unintuitive ... but I'm getting there, I think :grin:
How about some more maia?
 
![](http://imgur.com/rGwpBI0.png)

 :laughing: 
What do you think, @Chrysostomus @papajoker

**Comment by Chrysostomus** [comment]
Better colors than my current attempt, though work in progress. Background title could also be cyan

**Comment by Chrysostomus** [comment]
That dark gray text is not not sufficiently legible on that background though.

**Comment by oberon-manjaro** [comment]
which dark grey text do you mean?

**Comment by oberon-manjaro** [comment]
the inactive numbers? I didn't yet manage to find where they are defined ... :stuck_out_tongue:

**Comment by Chrysostomus** [comment]
Inactive numbers, yes

**Comment by oberon-manjaro** [comment]
The only place where I have set that darkest color is the shadow I think. But changing that value doesn't move them either ...

**Comment by oberon-manjaro** [comment]
I made a package with that stuff so we can test it on the ISO. It needs to be installed in the first place though for the systemd stuff to work and the config being copied to root's home -  will build a new ISO tomorrow. - Now off for some sleep ... ... :)

**Comment by oberon-manjaro** [comment]
**ma-console-colors**

**Comment by oberon-manjaro** [comment]
maybe those numbers take ``button_key_inactive_color``

**Comment by Chrysostomus** [comment]
Sleep well! You have done great!

**Comment by oberon-manjaro** [comment]
thank you! :)

**Comment by oberon-manjaro** [comment]
Got it now I think. :smile: 

 ![](http://imgur.com/oU7BAyw.png)

Might be that we find some places still in special dialog windows that will need some adjustment, but in general this is cracked I'd say. I'll just try some more things with that systemd service and might just make a console-maia package from that... openrc would need a different approach, but that's not really relevant for us, since there's really no need for the installer ISO to come with different init systems.

**Comment by Chrysostomus** [comment]
I might be switching console-solarized to console-maia then... Would be awesome if package supported openrc too, but not high priority

**Comment by oberon-manjaro** [comment]
Building it already :smiley: It will be **maia-console**. For openrc there seems to be a way via **/etc/issue** ... We can sort that out later :wink:

**Comment by oberon-manjaro** [comment]
@Chrysostomus after juggling around some more with colors I've just pushed **maia-console 1.2**, including an adjusted **dialogrc**. Dialog now looks pratically almost like before, but the theme now should work a lot better in the console also for ranger and stuff. Please check!
I'll have to rebuild the architect ISO with this, which is not a big deal... I will also do a 32bit additionally this time.

**Comment by oberon-manjaro** [comment]
The dialogrc will just work with maia-console only. It's an impossible task to do both I think: make the maia theme work and provide a dialog config that works for other themes. Try with three different terminal emulators and you get three completely different results. It also depends totally on the color profile your terminal uses, of course... ... So. It's just gonna have to be dialog default if not in the console and/or on the ISO I think.

**Comment by oberon-manjaro** [comment]
I'll make the text a little whiter still to make it more clearly readable... Also I can do a little better for the buttons - stay tuned :wink:

**Comment by oberon-manjaro** [comment]
**maia-console 1.2-2** :smile:

**Comment by oberon-manjaro** [comment]
ok. I now see that ranger uses magenta for regular highlight. That color is currently ugly, but there's no problem in changing it to whatever we like, since our new the dialogrc isn't using it anyway...

**Comment by Chrysostomus** [comment]
I'll test it tonight. I'm especially interested in in how it works together with zsh-syntax-highlighting that manjaro-zsh-config uses by default

**Comment by oberon-manjaro** [comment]
Hm. Let me know. But I'm a little afraid this is getting bottomless to serve all the different color customizations...

**Comment by Chrysostomus** [comment]
Worry not, we should be close to the finishing line :)

**Comment by oberon-manjaro** [comment]
**1.2-3** tested also with manajro zsh shell - maybe not ideal, but it works ok I think ...

**Comment by Chrysostomus** [comment]
Not on my mirror just yet. 1.2-3 was already a significant improvement. I'll test the next when I get it. 

Idea: would it be possible to assign that maia green to cyan?

**Comment by oberon-manjaro** [comment]
> assign that maia green to cyan

let me just find out what happens :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment]
Now online. It is better and worse than previous. Prompt gets diaplayed better, but syntax highlighting and autosuggestion colors are weird, as are man pages. Not unusable or hindering weird, just not as nice as they could be. 

I'll see if I can hack it a bit too...

**Comment by oberon-manjaro** [comment]
so. maia green on cyan works, in ranger just everything gets really bright and similar, in zsh shell i don't see a huge difference. What I still don't find good is how ranger displays image files. They are too dark...

**Comment by oberon-manjaro** [comment]
The problem with dialog is this:
When I look at for example how [solarized console theme](https://github.com/adeverteuil/console-solarized/blob/master/console-solarized) is organized: They leave colors 0-7 what their names actually are as the hightlight colors.
But with dialog we don't have the free choice to use colors 8-15 since it is only possible to specify the eight color names while in fact 16 colors are being applied in the end - kind of stupid!

**Comment by Chrysostomus** [comment]
I assume it applies the "bright" colors on bold text?

**Comment by Chrysostomus** [comment]
But yeah, sounds mighty inconvenient

**Comment by oberon-manjaro** [comment]
no. it's somehow associated to foreground and background as in screen(background)color vs dialog box I think. bold is dealt with separately as what it is and with terminus as we have it, not at all. Could we btw configure vconsole in a way that it uses normal and bold variants of terminus?

**Comment by Chrysostomus** [comment]
I don't think so, but I can be wrong

**Comment by oberon-manjaro** [comment]
yeah. I also assumed it's only possible in the terminal.

**Comment by Chrysostomus** [comment]
You could try http://stackoverflow.com/questions/2924697/how-does-one-output-bold-text-in-bash

If text doesn't get bolded, it may switch to bright variant instead

**Comment by oberon-manjaro** [comment]
we can live without bold I think. looks like this is all more for terminal anyway?

**Comment by oberon-manjaro** [comment]
the on/off property in the terminal btw works fine - for bold text, no color change! :wink:
