### ISSUE TITLE
uefi multi-manjaro

### ISSUE THREAD

**Issue by papajoker** [Chrysostomus/aif-dev#83]
always install in the same efi sub-directory "manjaro_grub" :(
https://github.com/Chrysostomus/manjaro-architect/search?utf8=%E2%9C%93&q=manjaro_grub

is a real problem or not ?
If there is already proposal to enter another name or crash

**Comment by Chrysostomus** [comment]
I don't think it is a major issue, but we could add a check to see if efi subdirectory exists. If it does, let user input new name. Keeping the same name would overwrite.

**Comment by sueridgepipe** [comment]
Calmares currently always installs into the subdirectory "Manjaro".

manjaro-architect always instlls into the subdirectory "manjaro-grub".

By changing this what issue are we fixing?  Does an issue exist?

**Comment by Chrysostomus** [comment]
I don't know. I changed arch-grub to manjaro-grub without knowing about what calamares does. Never installed with it.

**Comment by papajoker** [comment]
the issue is : 
if i change the grub location (possible with manjaro-architect) I have different grub according to the  uefi choise
With only one entry for all manjaro the other grub are present but inaccessible?
