### ISSUE TITLE
Set console font and keymap for openrc too

### ISSUE THREAD

**Issue by Chrysostomus** [Chrysostomus/aif-dev#84]
Openrc does not use vconsole.conf. Instead, font should be set in `/etc/conf.d/consolefont` and keymap in `/etc/conf.d/keymaps`. 

https://wiki.gentoo.org/wiki/Fonts#Console_font

https://wiki.gentoo.org/wiki/Keyboard_layout_switching#OpenRC

**Comment by Chrysostomus** [comment]
This should be fixed now, but I havent tested it yet

**Comment by oberon-manjaro** [comment]
fine now!
