### ISSUE TITLE
terminal spamming during final_check

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#86]
I've tried to quiet this with all sorts of /dev/nulling but seems I cannot stop a lot of output dirturbing the screen during final_check... Any idea?

**Comment by Chrysostomus** [comment]
What kind of output are you getting?

**Comment by oberon-manjaro** [comment]
it's so quick, I can't really catch it. I did see something including xargs and I even researched it. can't explain it now but it was nothing to be worried about. the rest I don't know. maybe it's the same multiple times. don't you see anything when you just mount a blank partition, then not install anything and then quit the installer?
It's not really a problem, it just looks messy I think ;)

**Comment by oberon-manjaro** [comment]
it's just the grep error messages basically. I just didn't find a way to dev null that without breaking the function. maybe you know how to do it properly ;)

**Comment by Chrysostomus** [comment]
Do final_check only if check_mount?

**Comment by oberon-manjaro** [comment]
we do that already :wink: 
```
if [[ $(lsblk -o MOUNTPOINT | grep ${MOUNTPOINT}) != "" ]]; then
        final_check
```

**Comment by oberon-manjaro** [comment]
but stuff like this has error output:
```
grep -qv '^#' /mnt/etc/fstab
```

**Comment by oberon-manjaro** [comment]
I guess I just don't have the right syntax to quiet it.
```
grep -qv '^#' /mnt/etc/fstab 2>/dev/null || echo "- Fstab has not been generated" >> ${CHECKLIST}
```
breaks the function

**Comment by oberon-manjaro** [comment]
maybe just needs brackets?
```
[[ grep ... ]] || ...
```

**Comment by Chrysostomus** [comment]
Put it in condition statement [[  -e /mnt/etc/fstab]]?

**Comment by Chrysostomus** [comment]
You could try brackets. Or making it into a function? 

        $(grep -qv '^#' /mnt/etc/fstab 2>/dev/null) || echo "- Fstab has not been generated"

**Comment by Chrysostomus** [comment]
Or 

grep -qv '^#' /mnt/etc/fstab >/dev/null 2>&1

**Comment by oberon-manjaro** [comment]
yeah. I just had this same idea: ``$(grep -qv '^#' /mnt/etc/fstab >/dev/null)`` seems to work :+1:

**Comment by oberon-manjaro** [comment]
Most are muted now :wink: I wasn't able to quiet the locales and root-pwd checks, but in any case I've made all checks conditional that don't make extra sense in case base wasn't installed anyway...
https://github.com/Chrysostomus/manjaro-architect/commit/b308bc90a0df32b5924c5279328c7689b10ba144 , https://github.com/Chrysostomus/manjaro-architect/commit/2a9b05cac81ad00d1b7e00a4dfbb1239864c26f7
