### ISSUE TITLE
automate base pkgs sync with iso-profiles repo

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#87]
Why are they not just processed from Packages-Root like the profile pkg-lists are?
Also I noticed that currently multilib is not really dealt with in the base install as far as i can see.

**Comment by Chrysostomus** [comment]
I've implemented this in basestrap_merge branch. Would have merged it, but the community found it undesirable.  I'll implement filtering for the main branch too.

**Comment by oberon-manjaro** [comment]
About the network thing that popped up on the forum: are we not installing all shared packages from iso-profiles? like **Packages-Mhwd** next to **Packages-Root**?

**Comment by Chrysostomus** [comment]
We are not and we should not, for the same reason we don't install Packages-Live. 90% of the list is unnecessary on any given system. We need other solutions
