### ISSUE TITLE
font for the live environment

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#88]
I'd like to use a terminus font or something similar more beautiful than the kernel builtin. Can you suggest which one would be good to use and how best to configure it on the ISO?

**Comment by Chrysostomus** [comment]
Vconsole.conf. Check out how the installer sets it

**Comment by oberon-manjaro** [comment]
its empty. terminus is not installed, yet. which of the many ter-fonts would you suggest. any idea how their system of letters and numers work, like ter-d16v ? b seems to be bold, n normal, but v? and the leading number/letter?

**Comment by Chrysostomus** [comment]
I would suggest the three options used by the installer. You can put in autostart 

       setfont <font_name>

https://wiki.archlinux.org/index.php/fonts#Preview_and_temporary_changes

**Comment by oberon-manjaro** [comment]
yes i've read that already. which "3 options used by the installer" do you mean?

**Comment by oberon-manjaro** [comment]
i only see three "speciality" fonts for Danish, Hungarian and Russian... you don't mean those, do you? :wink:

**Comment by oberon-manjaro** [comment]
terminus looks nice. maybe there are more that provide console fonts, i don't know. something like noto or so would be nice!?

**Comment by Chrysostomus** [comment]
The function that sets keymap also sets console font to Terminus

**Comment by oberon-manjaro** [comment]
yes. i know. so you mean we should just setfont at programm launch? I'd just love to have a more beautiful font already when the tty starts.
and I thought you had your favourite font right away that you'd want to see there ;) terminus is nice - maye that one for now... just have to check if vconsole.conf doesn't get overwritten by a package when I just put it in the overlay ... I'll try that tommorrow. :)

**Comment by oberon-manjaro** [comment]
```
The file names are structured as follows:

ter-u<SIZE><STYLE>.bdf

where <SIZE> is 12, 14, 16, 20, 24, 28 or 32, and <STYLE> is n for normal
(all sizes), b for bold (all sizes except 6x12) and v for EGA/VGA bold (8x14
and 8x16 only, makes use of the eight character matrix column).
``` 
:smile: :+1:

**Comment by oberon-manjaro** [comment]
Ok. works :) solved by installing terminus-font and using vconsole.conf in the overlay. Maybe will add some bold styling now in dialog with the different font. But I think customization is done ;) Looks quite cool now I think.

![](http://imgur.com/TvvAfLV.png)

![](http://imgur.com/I084JDi.png)
