### ISSUE TITLE
make sure the selected default shell is actually installed

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#90]
https://forum.manjaro.org/t/experimental-manjaro-architect-test-iso/17661/161
Looks like we are not checking at first glance..., or are we?

**Comment by Chrysostomus** [comment]
Not yet. We need to check if we drop installation of extra packages. Also, we need to make sure that zsh is configured if chosen. 

For fish, installing fish is enough. For zsh 

if ! [[ -e /mnt/usr/bin/zsh ]]; then 
    basestrap /mnt zsh
fi

if ! [[ -e /mnt/etc/skel/.zshrc ]]; then 
    basestrap /mnt manjaro-zsh-config
fi

**Comment by oberon-manjaro** [comment]
I'm just installing zsh config now, since it depends on zsh anyway. In case selection would be empty we're falling back to bash, since it's installed anyway. Ok for you?

**Comment by Chrysostomus** [comment]
Ok
