### ISSUE TITLE
aborting pacman-keys exits app

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#91]
I have tried all sorts of things but no matter what. When you hit Ctrl+C during pacman-keys, the installer will exit altogether.
I've tried loops here and there, wrapping those command in a separate function. Doesn't work.
At the same time, during pacman -Syy it's no problem. So it looks like pacman-keys is sending a bad message back to our program.
The only thing that sort of works is sending the wrapper function to the background with ``packeys &`` or whatever. The problem with that is that console output during pacman-keys gets completely messed up. You can however cancel that process with Ctrl+C :stuck_out_tongue_winking_eye: 
It would just be nice to get this to work since this procedure takes really quite a long time and so it wouldn't be bad to have an option to change your mind and leave ...
Any ideas? @Chrysostomus @papajoker ?

**Comment by papajoker** [comment]
```
        "2") clear
             (
                 ctrlc() {
                      exit 0
                 }
                trap ctrlc SIGINT        # call my function
                trap ctrlc SIGTERM    # call my function
                pacman-key --init;pacman-key --populate archlinux manjaro;pacman-key --refresh-keys;
                check_for_error 'refresh pacman-keys'
              )

```
its ok for make a ctrl+C but you dont close manjaro-architect
create a sub-shell and intercept ctrl+c

**Comment by oberon-manjaro** [comment]
Awesome, thank you! But is it really ``exit 0`` here? not ``return 0``?

**Comment by oberon-manjaro** [comment]
fixed now. Thanks @papajoker
