### ISSUE TITLE
base install ERROR

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#94]
weird:
![](http://imgur.com/PXsnw8L.png)

I don't understand what's going on there.
We are at
```
filter_packages
check_for_error "packages to install: $(cat /mnt/.base | tr '\n' ' ')"
# If at least one kernel selected, proceed with installation.
basestrap ${MOUNTPOINT} $(cat /mnt/.base) 2>$ERR
check_for_error "install basepkgs" $?
```
A manual ``cat /mnt/.base`` gives me a nice list of packages. Why does it say ``cat : ' ' : No such file or directory`` ?

**Comment by papajoker** [comment]
error is at line basestrap 
if basestrap we hare in /mnt/ ? good path ?  is : 

     basestrap ${MOUNTPOINT} $(cat .base) 2>$ERR

or 

     local fbase=$(</mnt/.base)
     basestrap ${MOUNTPOINT} $(fbase) 2>$ERR

**Comment by Chrysostomus** [comment]
It's because same filter packages function is used for both base installation and desktop installation. Fixed in the local branch, pushing soon

**Comment by oberon-manjaro** [comment]
Uhm. Oops, not fixed!

![](http://imgur.com/OA1Hjq3.png)

**Comment by oberon-manjaro** [comment]
Also, both of @papajoker 's suggestions give the same error - but funny: why packages are being intalled anyway??

**Comment by oberon-manjaro** [comment]
In fact, looking at the code again:
```
filter_packages
check_for_error "packages to install: $(cat /mnt/.base | tr '\n' ' ')"
# If at least one kernel selected, proceed with installation.
basestrap ${MOUNTPOINT} $(cat /mnt/.base) 2>$ERR
check_for_error "install basepkgs" $?
```
That error, appended in the same line as the packages... seems not to belong to ``check_for_error`` after ``basestrap`` but simply to the logging one before - so, most likely we can just forget about it.
If the error would belong to the basestrap command it would need to come after "install basepkgs", right!
I just don't understand where it comes from.
We can maybe just 2>/dev/null that first line. The output remains a mystery to me however! :wink:

**Comment by oberon-manjaro** [comment]
Mystery solved! :laughing: 
The error actually belongs to ``filter_packages()`` where at the begin we had a ``2>$ERR``, not followed by an error check.
So the real error here is this:

![](http://imgur.com/nwRrvI4l.png)

**Comment by oberon-manjaro** [comment]
The problem here is that ``$target_desktop`` hasn't been defined, yet. This will only happen in **install_manjaro_de_wm()**

**Comment by Chrysostomus** [comment]
I tried to make a if statement that would cat that only if /tmp/.desktop is present, but apparently it checks for it anyway...

**Comment by oberon-manjaro** [comment]
I'm almost done with a new xfce install. Filtering seems to work as it should and no error in log.
:+1:
