### ISSUE TITLE
check_base needed before install_drivers_menu ?

### ISSUE THREAD

**Issue by oberon-manjaro** [Chrysostomus/aif-dev#98]
I think drivers cannot be installed before base packages have, right?
In any case attempting that fails with
```
mountpoint /mnt/proc doesn't exist
```

**Comment by Chrysostomus** [comment]
Makes sense.

**Comment by oberon-manjaro** [comment]
``install_manjaro_de_wm_pkg`` entry also needed one :wink: 
I've now just moved the checks to functions and submenus instead of individual menu entries. Like that we don't have to bother about that whenever we change menus in the future
https://github.com/Chrysostomus/manjaro-architect/commit/48ab6b425b21b7caebadcff8b1fd9c9fab003bbb
